In [31]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 25.1.1
[notice] To update, run: C:\Users\Alice\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [32]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: scipy in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.14.1)
Requirement already satisfied: numpy<2.3,>=1.23.5 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scipy) (2.1.3)

[notice] A new release of pip is available: 25.0 -> 25.1.1
[notice] To update, run: C:\Users\Alice\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# Preparação dos dados

In [33]:
# Importação da biblioteca pandas para manipulação de dados
import pandas as pd

# Caminhos para os arquivos CSV
file_path = './csv_recebidos/Distâncias_aeroportos.csv'  # Arquivo com as distâncias entre aeroportos
file_path1 = './csv_recebidos/Nome_Aeroporto.csv'  # Arquivo com os nomes dos aeroportos

# Carrega os arquivos CSV em DataFrames
df = pd.read_csv(file_path)  # DataFrame com as distâncias
df_nome = pd.read_csv(file_path1)  # DataFrame com os nomes dos aeroportos

df

      InputID  TargetID  Distance (km)
0          91         1           2183
1          91         2            108
2          91         3            737
3          91         4            155
4          91         5           1145
...       ...       ...            ...
8185        1        87           1233
8186        1        88           9327
8187        1        89           7487
8188        1        90           2070
8189        1        91           2183

[8190 rows x 3 columns]

In [34]:
# Renomeia as colunas do DataFrame de distâncias
df.columns = ["InputID", "TargetID", "Distância km"]
df

      InputID  TargetID  Distância km
0          91         1          2183
1          91         2           108
2          91         3           737
3          91         4           155
4          91         5          1145
...       ...       ...           ...
8185        1        87          1233
8186        1        88          9327
8187        1        89          7487
8188        1        90          2070
8189        1        91          2183

[8190 rows x 3 columns]

In [35]:
# Cria um mapeamento de IDs para nomes dos aeroportos
mapa_ids = {i+1: nome for i, nome in enumerate(df_nome['Aeroporto'])}

# Substitui os IDs nas colunas 'InputID' e 'TargetID' pelos nomes dos aeroportos
df['InputID'] = df['InputID'].replace(mapa_ids)
df['TargetID'] = df['TargetID'].replace(mapa_ids)
# Adiciona uma coluna de emissão de CO2 com base na distância

df

,InputID,TargetID,Distância km
0,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Guarulhos,2183
1,Aeroporto Internacional de João Pessoa,Aeroporto Internacional do Recife,108
2,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Salvador,737
3,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Natal,155
4,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de São Luís,1145
...,...,...,...
8185,Aeroporto Internacional de Guarulhos,Aeroporto Jorge Amado,1233
8186,Aeroporto Internacional de Guarulhos,Aeroporto de Copenhague,9327
8187,Aeroporto Internacional de Guarulhos,Aeroporto Internacional Hartsfield-Jackson Atl...,7487
8188,Aeroporto Internacional de Guarulhos,Aeroporto de Teresina,2070
8189,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de João Pessoa,2183

In [36]:
# Função para formatar horas no formato HH:MM
def format_time(hours):
    h = int(hours)
    m = int((hours - h) * 60)
    return f"{h:02}:{m:02}"

# Calcula o tempo médio de voo para aeronaves comerciais
df['Tempo Médio Horas - Comercial'] = df['Distância km'].apply(
    lambda d: f"{format_time(d / 900)} ~ {format_time(d / 850)}"
)

# Calcula o tempo médio de voo para aeronaves cargueiras
df['Tempo Médio Horas - Cargueiro'] = df['Distância km'].apply(
    lambda d: f"{format_time(d / 850)} ~ {format_time(d / 800)}"
)

df.to_csv('./csv_gerado/Tabela_Básica.csv', index=False)

In [37]:
df

,InputID,TargetID,Distância km,Tempo Médio Horas - Comercial,Tempo Médio Horas - Cargueiro
0,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Guarulhos,2183,02:25 ~ 02:34,02:34 ~ 02:43
1,Aeroporto Internacional de João Pessoa,Aeroporto Internacional do Recife,108,00:07 ~ 00:07,00:07 ~ 00:08
2,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Salvador,737,00:49 ~ 00:52,00:52 ~ 00:55
3,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Natal,155,00:10 ~ 00:10,00:10 ~ 00:11
4,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de São Luís,1145,01:16 ~ 01:20,01:20 ~ 01:25
...,...,...,...,...,...
8185,Aeroporto Internacional de Guarulhos,Aeroporto Jorge Amado,1233,01:22 ~ 01:27,01:27 ~ 01:32
8186,Aeroporto Internacional de Guarulhos,Aeroporto de Copenhague,9327,10:21 ~ 10:58,10:58 ~ 11:39
8187,Aeroporto Internacional de Guarulhos,Aeroporto Internacional Hartsfield-Jackson Atl...,7487,08:19 ~ 08:48,08:48 ~ 09:21
8188,Aeroporto Internacional de Guarulhos,Aeroporto de Teresina,2070,02:17 ~ 02:26,02:26 ~ 02:35
8189,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de João Pessoa,2183,02:25 ~ 02:34,02:34 ~ 02:43

In [38]:
# Lista de aeroportos de interesse
aeroportos_interesse = [
    "Aeroporto Internacional de Guarulhos",
    "Aeroporto Internacional do Recife",
    "Aeroporto Internacional de Salvador",
    "Aeroporto Internacional de Natal",
    "Aeroporto Internacional de São Luís",
    "Aeroporto Internacional de Fortaleza",
    "Aeroporto Internacional de Brasília",
    "Aeroporto Internacional de Várzea Grande",
    "Aeroporto Internacional de Belém",
    "Aeroporto Internacional de Tabatinga",
    "Aeroporto Internacional de Manaus",
    "Aeroporto Internacional de Macapá",
    "Aeroporto Internacional de Maceió",
    "Aeroporto Internacional de Aracaju",
    "Aeroporto Internacional de Belo Horizonte",
    "Aeroporto Santos Dumont",
    "Aeroporto Internacional do Rio de Janeiro",
    "Aeroporto Internacional de Vitória",
    "Aeroporto Internacional de São José dos Campos",
    "Aeroporto Internacional de Viracopos",
    "Aeroporto Internacional de Curitiba",
    "Aeroporto Internacional de Florianópolis",
    "Aeroporto Internacional de Navegantes",
    "Aeroporto Internacional de Porto Alegre",
    "Aeroporto Internacional de Boa Vista",
    "Aeroporto de Teresina",
    "Aeroporto Internacional de João Pessoa",
    "Aeroporto Jorge Amado"
]

# Gera uma lista de aeroportos de origem únicos
lista_origem = df['InputID'].unique().tolist()

# Remove os aeroportos de interesse da lista de origem
for i in aeroportos_interesse:
    try:
        lista_origem.remove(i)
    except ValueError:
        pass

lista_origem

['Aeroporto Internacional Hartsfield-Jackson Atlanta',
 'Aeroporto de Copenhague',
 'Aeroporto de Helsinque',
 'Aeroporto de Vágar',
 'Aeroporto de Tallinn',
 'Aeroporto de Barcelona-El Prat',
 'Aeroporto Adolfo Suárez Madrid-Barajas',
 'Aeroporto de Ljubljana Jo\x9ee Pu?nik',
 'Aeroporto de Bratislava',
 'Aeroporto de Sófia',
 'Aeroporto de Bruxelas',
 'Aeroporto Internacional de Viena',
 'Aeroporto de Toulouse-Blagnac (França)',
 'Aeroporto de Barcelona-El Prat (Espanha)',
 'Aeroporto Internacional Madre Teresa (Tirana)',
 'Aeroporto Internacional de Riga',
 'Aeroporto Internacional de Vilnius',
 'Aeroporto de Luxemburgo',
 'Aeroporto Internacional de Malta',
 'Aeroporto Francisco Sá Carneiro (Porto)',
 'Aeroporto Humberto Delgado (Lisboa)',
 'Aeroporto Internacional Henri Coand? (Bucareste)',
 'Aeroporto de Pulkovo (São Petersburgo)',
 'Aeroporto Internacional Sheremetyevo (Moscou)',
 'Aeroporto Nikola Tesla (Belgrado)',
 'Aeroporto de Estocolmo-Arlanda',
 'Aeroporto de Zurique',
 'Aeroporto de Istambul',
 'Aeroporto Internacional de Boryspil (Kiev)',
 'Aeroporto de Schiphol (Amsterdã)',
 'Aeroporto Internacional de Budapeste Ferenc Liszt',
 'Aeroporto de Gatwick (Londres)',
 'Aeroporto de Heathrow (Londres)',
 'Aeroporto de Praga',
 'Aeroporto de Milão-Malpensa',
 'Aeroporto de Roma-Fiumicino',
 'Aeroporto de Oslo-Gardermoen',
 'Aeroporto de Varsóvia Chopin',
 'Aeroporto de Dublin',
 'Aeroporto de Frankfurt',
 'Aeroporto Internacional de Noi Bai',
 'Aeroporto Internacional de Tan Son Nhat',
 'Aeroporto Internacional de Taiwan Taoyuan',
 'Aeroporto Internacional Don Mueang',
 'Aeroporto Internacional de Suvarnabhumi',
 'Aeroporto Internacional de Changi',
 'Aeroporto Internacional de Malé',
 'Aeroporto Internacional de Penang (Penang)',
 'Aeroporto Internacional de Kuala Lumpur (Sepang)',
 'Aeroporto Internacional de Wattay (Vientiane)',
 'Aeroporto Internacional de Kansai (Osaka)',
 'Aeroporto Internacional de Haneda (Tóquio)',
 'Aeroporto Internacional de Narita (Tóquio)',
 'Aeroporto Internacional Ngurah Rai (Bali)',
 'Aeroporto Internacional Soekarno-Hatta (Jacarta)',
 'Aeroporto Internacional Indira Gandhi',
 'Aeroporto Internacional de Hong Kong',
 'Aeroporto Internacional Ninoy Aquino',
 'Aeroporto Internacional de Incheon',
 'Aeroporto Internacional de Pyongyang Sunan',
 'Aeroporto Internacional de Pequim Capital',
 'Aeroporto Internacional de Xangai Pudong',
 'Aeroporto Internacional de Nursultan Nazarbayev',
 'Aeroporto Internacional Pinto Martins']

In [39]:
aeroportos_estado = {
    "Alagoas": ["Aeroporto Internacional de Maceió"],
    "Amapá": ["Aeroporto Internacional de Macapá"],
    "Amazonas": [
        "Aeroporto Internacional de Tabatinga",
        "Aeroporto Internacional de Manaus"
    ],
    "Bahia": ["Aeroporto Internacional de Salvador"],
    "Ceará": ["Aeroporto Internacional de Fortaleza"],
    "Espírito Santo": ["Aeroporto Internacional de Vitória"],
    "Maranhão": ["Aeroporto Internacional de São Luís"],
    "Mato Grosso": ["Aeroporto Internacional de Brasília"],
    "Minas Gerais": ["Aeroporto Internacional de Belo Horizonte"],
    "Pará": ["Aeroporto Internacional de Belém"],
    "Paraíba" : ["Aeroporto Internacional de João Pessoa"],
    "Paraná": ["Aeroporto Internacional de Curitiba"],
    "Pernambuco": ["Aeroporto Internacional do Recife"],
    "Piauí": ["Aeroporto de Teresina"],
    "Rio de Janeiro": [
        "Aeroporto Santos Dumont",
        "Aeroporto Internacional do Rio de Janeiro"
    ],
    "Rio Grande do Norte": ["Aeroporto Internacional de Natal"],
    "Rio Grande do Sul": ["Aeroporto Internacional de Porto Alegre"],
    "Roraima": ["Aeroporto Internacional de Boa Vista"],
    "Santa Catarina": [
        "Aeroporto Internacional de Florianópolis",
        "Aeroporto Internacional de Navegantes"
    ],
    "São Paulo": [
        "Aeroporto Internacional de Guarulhos",
        "Aeroporto Internacional de São José dos Campos",
        "Aeroporto Internacional de Viracopos"
    ],
    "Sergipe": ["Aeroporto Internacional de Aracaju"]
}

# Tabela completa

In [40]:
# Lista para armazenar os resultados
result = []

# Itera sobre todos os aeroportos de origem na lista_origem
for aeroporto_origem in lista_origem:
    # Inicializa um dicionário para armazenar os dados de cada aeroporto de destino
    dados_aeroportos = {estado_destino: [None, None, None] for estado_destino in aeroportos_estado.keys()}
    
    # Itera sobre os aeroportos de destino
    for estado_destino, aeroporto_destino in aeroportos_estado.items():
        # Seleciona a linha com informações sobre o aeroporto de origem e destino
        linha = df.loc[(df['InputID'] == aeroporto_origem) & (df['TargetID'] == aeroporto_destino[0])]
        
        if not linha.empty:  # Verifica se há dados para a combinação de aeroportos
            # Extrai os valores necessários da linha
            distancia = linha['Distância km'].values[0]
            tempo_comercial = linha['Tempo Médio Horas - Comercial'].values[0]
            tempo_carga = linha['Tempo Médio Horas - Cargueiro'].values[0]
            
            # Atualiza os dados do estado de destino
            dados_aeroportos[estado_destino] = [distancia, tempo_comercial, tempo_carga]

    # Prepara os dados para o aeroporto de origem atual
    dados_origem = {"Origem": aeroporto_origem}
    for estado_destino, valores in dados_aeroportos.items():
        dados_origem.update({
            f"{estado_destino} (Km)": valores[0],
            f"{estado_destino} (Hr - Comercial)": valores[1],
            f"{estado_destino} (Hr - Cargueiro)": valores[2],
        })
    
    # Adiciona os dados ao resultado
    result.append(dados_origem)

# Transforma o resultado em um DataFrame
df_result = pd.DataFrame(result)

df_result

,Origem,Alagoas (Km),Alagoas (Hr - Comercial),Alagoas (Hr - Cargueiro),Amapá (Km),Amapá (Hr - Comercial),Amapá (Hr - Cargueiro),Amazonas (Km),Amazonas (Hr - Comercial),Amazonas (Hr - Cargueiro),...,Roraima (Hr - Cargueiro),Santa Catarina (Km),Santa Catarina (Hr - Comercial),Santa Catarina (Hr - Cargueiro),São Paulo (Km),São Paulo (Hr - Comercial),São Paulo (Hr - Cargueiro),Sergipe (Km),Sergipe (Hr - Comercial),Sergipe (Hr - Cargueiro)
0,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,07:45 ~ 08:12,08:12 ~ 08:43,5096,05:39 ~ 05:59,05:59 ~ 06:22,4517,05:01 ~ 05:18,05:18 ~ 05:38,...,None,7771,08:38 ~ 09:08,09:08 ~ 09:42,7487,08:19 ~ 08:48,08:48 ~ 09:21,7032,07:48 ~ 08:16,08:16 ~ 08:47
1,Aeroporto de Copenhague,7479,08:18 ~ 08:47,08:47 ~ 09:20,7071,07:51 ~ 08:19,08:19 ~ 08:50,8146,09:03 ~ 09:35,09:35 ~ 10:10,...,None,9839,10:55 ~ 11:34,11:34 ~ 12:17,9327,10:21 ~ 10:58,10:58 ~ 11:39,7719,08:34 ~ 09:04,09:04 ~ 09:38
2,Aeroporto de Helsinque,9338,10:22 ~ 10:59,10:59 ~ 11:40,9236,10:15 ~ 10:51,10:51 ~ 11:32,10395,11:33 ~ 12:13,12:13 ~ 12:59,...,None,11789,13:05 ~ 13:52,13:52 ~ 14:44,11277,12:31 ~ 13:16,13:16 ~ 14:05,9592,10:39 ~ 11:17,11:17 ~ 11:59
3,Aeroporto de Vágar,8260,09:10 ~ 09:43,09:43 ~ 10:19,7794,08:39 ~ 09:10,09:10 ~ 09:44,8783,09:45 ~ 10:19,10:19 ~ 10:58,...,None,10608,11:47 ~ 12:28,12:28 ~ 13:15,10097,11:13 ~ 11:52,11:52 ~ 12:37,8499,09:26 ~ 09:59,09:59 ~ 10:37
4,Aeroporto de Tallinn,9280,10:18 ~ 10:55,10:55 ~ 11:35,9207,10:13 ~ 10:49,10:49 ~ 11:30,10385,11:32 ~ 12:13,12:13 ~ 12:58,...,None,11733,13:02 ~ 13:48,13:48 ~ 14:39,11222,12:28 ~ 13:12,13:12 ~ 14:01,9534,10:35 ~ 11:12,11:12 ~ 11:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Aeroporto Internacional de Pyongyang Sunan,16188,17:59 ~ 19:02,19:02 ~ 20:14,15644,17:22 ~ 18:24,18:24 ~ 19:33,15853,17:36 ~ 18:39,18:39 ~ 19:48,...,None,18618,20:41 ~ 21:54,21:54 ~ 23:16,18106,20:07 ~ 21:18,21:18 ~ 22:37,16441,18:16 ~ 19:20,19:20 ~ 20:33
60,Aeroporto Internacional de Pequim Capital,15617,17:21 ~ 18:22,18:22 ~ 19:31,15391,17:06 ~ 18:06,18:06 ~ 19:14,15927,17:41 ~ 18:44,18:44 ~ 19:54,...,None,18075,20:04 ~ 21:15,21:15 ~ 22:35,17578,19:31 ~ 20:40,20:40 ~ 21:58,15873,17:38 ~ 18:40,18:40 ~ 19:50
61,Aeroporto Internacional de Xangai Pudong,16641,18:29 ~ 19:34,19:34 ~ 20:48,16473,18:18 ~ 19:22,19:22 ~ 20:35,16815,18:41 ~ 19:46,19:46 ~ 21:01,...,None,19014,21:07 ~ 22:22,22:22 ~ 23:46,18581,20:38 ~ 21:51,21:51 ~ 23:13,16896,18:46 ~ 19:52,19:52 ~ 21:07
62,Aeroporto Internacional de Nursultan Nazarbayev,11988,13:19 ~ 14:06,14:06 ~ 14:59,12209,13:33 ~ 14:21,14:21 ~ 15:15,13424,14:54 ~ 15:47,15:47 ~ 16:46,...,None,14423,16:01 ~ 16:58,16:58 ~ 18:01,13941,15:29 ~ 16:24,16:24 ~ 17:25,12243,13:36 ~ 14:24,14:24 ~ 15:18
63,Aeroporto Internacional Pinto Martins,659,00:43 ~ 00:46,00:46 ~ 00:49,1458,01:37 ~ 01:42,01:42 ~ 01:49,3082,03:25 ~ 03:37,03:37 ~ 03:51,...,None,2851,03:10 ~ 03:21,03:21 ~ 03:33,2337,02:35 ~ 02:44,02:44 ~ 02:55,809,00:53 ~ 00:57,00:57 ~ 01:00

In [41]:
# Ordena o DataFrame pela coluna "Distrito Federal (Km)"
df_result_sorted = df_result.reset_index(drop=True)

# Exporta o DataFrame ordenado para um arquivo CSV
df_result_sorted.to_csv('./csv_gerado/Tabela_Completa.csv', index=False)

df_result_sorted

,Origem,Alagoas (Km),Alagoas (Hr - Comercial),Alagoas (Hr - Cargueiro),Amapá (Km),Amapá (Hr - Comercial),Amapá (Hr - Cargueiro),Amazonas (Km),Amazonas (Hr - Comercial),Amazonas (Hr - Cargueiro),...,Roraima (Hr - Cargueiro),Santa Catarina (Km),Santa Catarina (Hr - Comercial),Santa Catarina (Hr - Cargueiro),São Paulo (Km),São Paulo (Hr - Comercial),São Paulo (Hr - Cargueiro),Sergipe (Km),Sergipe (Hr - Comercial),Sergipe (Hr - Cargueiro)
0,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,07:45 ~ 08:12,08:12 ~ 08:43,5096,05:39 ~ 05:59,05:59 ~ 06:22,4517,05:01 ~ 05:18,05:18 ~ 05:38,...,None,7771,08:38 ~ 09:08,09:08 ~ 09:42,7487,08:19 ~ 08:48,08:48 ~ 09:21,7032,07:48 ~ 08:16,08:16 ~ 08:47
1,Aeroporto de Copenhague,7479,08:18 ~ 08:47,08:47 ~ 09:20,7071,07:51 ~ 08:19,08:19 ~ 08:50,8146,09:03 ~ 09:35,09:35 ~ 10:10,...,None,9839,10:55 ~ 11:34,11:34 ~ 12:17,9327,10:21 ~ 10:58,10:58 ~ 11:39,7719,08:34 ~ 09:04,09:04 ~ 09:38
2,Aeroporto de Helsinque,9338,10:22 ~ 10:59,10:59 ~ 11:40,9236,10:15 ~ 10:51,10:51 ~ 11:32,10395,11:33 ~ 12:13,12:13 ~ 12:59,...,None,11789,13:05 ~ 13:52,13:52 ~ 14:44,11277,12:31 ~ 13:16,13:16 ~ 14:05,9592,10:39 ~ 11:17,11:17 ~ 11:59
3,Aeroporto de Vágar,8260,09:10 ~ 09:43,09:43 ~ 10:19,7794,08:39 ~ 09:10,09:10 ~ 09:44,8783,09:45 ~ 10:19,10:19 ~ 10:58,...,None,10608,11:47 ~ 12:28,12:28 ~ 13:15,10097,11:13 ~ 11:52,11:52 ~ 12:37,8499,09:26 ~ 09:59,09:59 ~ 10:37
4,Aeroporto de Tallinn,9280,10:18 ~ 10:55,10:55 ~ 11:35,9207,10:13 ~ 10:49,10:49 ~ 11:30,10385,11:32 ~ 12:13,12:13 ~ 12:58,...,None,11733,13:02 ~ 13:48,13:48 ~ 14:39,11222,12:28 ~ 13:12,13:12 ~ 14:01,9534,10:35 ~ 11:12,11:12 ~ 11:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Aeroporto Internacional de Pyongyang Sunan,16188,17:59 ~ 19:02,19:02 ~ 20:14,15644,17:22 ~ 18:24,18:24 ~ 19:33,15853,17:36 ~ 18:39,18:39 ~ 19:48,...,None,18618,20:41 ~ 21:54,21:54 ~ 23:16,18106,20:07 ~ 21:18,21:18 ~ 22:37,16441,18:16 ~ 19:20,19:20 ~ 20:33
60,Aeroporto Internacional de Pequim Capital,15617,17:21 ~ 18:22,18:22 ~ 19:31,15391,17:06 ~ 18:06,18:06 ~ 19:14,15927,17:41 ~ 18:44,18:44 ~ 19:54,...,None,18075,20:04 ~ 21:15,21:15 ~ 22:35,17578,19:31 ~ 20:40,20:40 ~ 21:58,15873,17:38 ~ 18:40,18:40 ~ 19:50
61,Aeroporto Internacional de Xangai Pudong,16641,18:29 ~ 19:34,19:34 ~ 20:48,16473,18:18 ~ 19:22,19:22 ~ 20:35,16815,18:41 ~ 19:46,19:46 ~ 21:01,...,None,19014,21:07 ~ 22:22,22:22 ~ 23:46,18581,20:38 ~ 21:51,21:51 ~ 23:13,16896,18:46 ~ 19:52,19:52 ~ 21:07
62,Aeroporto Internacional de Nursultan Nazarbayev,11988,13:19 ~ 14:06,14:06 ~ 14:59,12209,13:33 ~ 14:21,14:21 ~ 15:15,13424,14:54 ~ 15:47,15:47 ~ 16:46,...,None,14423,16:01 ~ 16:58,16:58 ~ 18:01,13941,15:29 ~ 16:24,16:24 ~ 17:25,12243,13:36 ~ 14:24,14:24 ~ 15:18
63,Aeroporto Internacional Pinto Martins,659,00:43 ~ 00:46,00:46 ~ 00:49,1458,01:37 ~ 01:42,01:42 ~ 01:49,3082,03:25 ~ 03:37,03:37 ~ 03:51,...,None,2851,03:10 ~ 03:21,03:21 ~ 03:33,2337,02:35 ~ 02:44,02:44 ~ 02:55,809,00:53 ~ 00:57,00:57 ~ 01:00

# Dataset resumidos - por distância, horas de voo em avião comercial e de carga.

In [42]:
# Cria DataFrames separados para distâncias, emissões, tempos comerciais e tempos de carga
df_distancias = df_result.filter(["Origem"] + [f"{estado} (Km)" for estado in aeroportos_estado.keys()])
df_tempo_comercial = df_result.filter(["Origem"] + [f"{estado} (Hr - Comercial)" for estado in aeroportos_estado.keys()])
df_tempo_carga = df_result.filter(["Origem"] + [f"{estado} (Hr - Cargueiro)" for estado in aeroportos_estado.keys()])

# Exporta os DataFrames para arquivos CSV
df_distancias.to_csv('./csv_gerado/Tabela_Distâncias.csv', index=False)
df_tempo_comercial.to_csv('./csv_gerado/Tabela_Tempo_Comercial.csv', index=False)
df_tempo_carga.to_csv('./csv_gerado/Tabela_Tempo_Carga.csv', index=False)

# Exibe o DataFrame de distâncias
df_distancias

,Origem,Alagoas (Km),Amapá (Km),Amazonas (Km),Bahia (Km),Ceará (Km),Espírito Santo (Km),Maranhão (Km),Mato Grosso (Km),Minas Gerais (Km),...,Paraná (Km),Pernambuco (Km),Piauí (Km),Rio de Janeiro (Km),Rio Grande do Norte (Km),Rio Grande do Sul (Km),Roraima (Km),Santa Catarina (Km),São Paulo (Km),Sergipe (Km)
0,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,5096,4517,7099,6353,7583,5818,6709,7337,...,7510,6975,6124,7635,6768,7864,None,7771,7487,7032
1,Aeroporto de Copenhague,7479,7071,8146,7965,6997,8804,7065,8585,8823,...,9607,7359,7273,9169,7116,10168,None,9839,9327,7719
2,Aeroporto de Helsinque,9338,9236,10395,9847,8953,10668,9128,10615,10747,...,11587,9208,9297,11066,8990,12140,None,11789,11277,9592
3,Aeroporto de Vágar,8260,7794,8783,8743,7771,9582,7823,9345,9597,...,10373,8140,8038,9945,7896,10934,None,10608,10097,8499
4,Aeroporto de Tallinn,9280,9207,10385,9790,8902,10608,9086,10568,10691,...,11534,9149,9251,11007,8933,12086,None,11733,11222,9534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Aeroporto Internacional de Pyongyang Sunan,16188,15644,15853,16696,15769,17515,15821,17343,17589,...,18383,16057,16048,17915,15838,18941,None,18618,18106,16441
60,Aeroporto Internacional de Pequim Capital,15617,15391,15927,16130,15277,16907,15429,16936,17040,...,17901,15483,15617,17323,15285,18438,None,18075,17578,15873
61,Aeroporto Internacional de Xangai Pudong,16641,16473,16815,17150,16349,17863,16524,18024,18050,...,18921,16506,16706,18277,16326,19342,None,19014,18581,16896
62,Aeroporto Internacional de Nursultan Nazarbayev,11988,12209,13424,12498,11725,13249,12004,13412,13404,...,14275,11852,12128,13667,11673,14786,None,14423,13941,12243
63,Aeroporto Internacional Pinto Martins,659,1458,3082,1011,1,1833,647,1688,1826,...,2636,625,498,2175,425,3193,None,2851,2337,809

# Recebendo Voos_Nordeste

In [43]:
file_path = './csv_recebidos/Voos_Nordeste.csv'  # Arquivo com os nomes dos aeroportos

# Carrega os arquivos CSV em DataFrames
df_nordeste = pd.read_csv(file_path)  # DataFrame com as distâncias
df_nordeste

,UF do Produto,URF,Código NCM,Países,Quantidades - (2020-2025),Frete - (2020-2025),Frete Total
0,Alagoas,Aeroporto Internacional de Guarulhos,84715010,Estados Unidos,10,1091,10910
1,Bahia,Aeroporto Internacional de Salvador,84715020,Estados Unidos,10,1416,14160
2,Pernambuco,Aeroporto Internacional de Guarulhos,84715010,China,28,92,2576
3,Rio Grande do Norte,Aeroporto Internacional de Guarulhos,84715010,"Tcheca, República",2,464,928
4,Alagoas,Aeroporto Internacional do Recife,84715030,Estados Unidos,1,624,624
...,...,...,...,...,...,...,...
344,Maranhão,Aeroporto Internacional de Fortaleza,84715010,China,2,22,44
345,Pernambuco,Aeroporto Internacional do Recife,84715010,Polônia,3,779,2337
346,Bahia,Aeroporto Internacional de Salvador,84715010,China,1,33,33
347,Bahia,Aeroporto Internacional de Salvador,84715010,Estados Unidos,2,403,806
348,Ceará,Aeroporto Internacional de Fortaleza,84715010,Alemanha,6,620,3720

# Grafo - Rota Original

In [44]:
aeroportos_nordeste = {"Alagoas": ["Aeroporto Internacional de Maceió"],
    "Bahia": ["Aeroporto Internacional de Salvador"],
    "Ceará": ["Aeroporto Internacional de Fortaleza"],
    "Maranhão": ["Aeroporto Internacional de São Luís"],
    "Paraíba": ["Aeroporto Internacional de João Pessoa"],
    "Pernambuco": ["Aeroporto Internacional do Recife"],
    "Piauí": ["Aeroporto de Teresina"],
    "Rio Grande do Norte": ["Aeroporto Internacional de Natal"],
    "Sergipe": ["Aeroporto Internacional de Aracaju"]}

lista_estados = list(aeroportos_nordeste.keys())
lista_estados

['Alagoas',
 'Bahia',
 'Ceará',
 'Maranhão',
 'Paraíba',
 'Pernambuco',
 'Piauí',
 'Rio Grande do Norte',
 'Sergipe']

In [45]:
aeroportos_exterior = {
    "Albânia": ["Aeroporto Internacional Madre Teresa (Tirana)"],
    "Alemanha": ["Aeroporto de Frankfurt"],
    "Andorra": [
        "Aeroporto de Barcelona-El Prat (Espanha)",
        "Aeroporto de Toulouse-Blagnac (França)"
    ],
    "Áustria": ["Aeroporto Internacional de Viena"],
    "Bélgica": ["Aeroporto de Bruxelas"],
    "Bulgária": ["Aeroporto de Sófia"],
    "Cazaquistão": ["Aeroporto Internacional de Nursultan Nazarbayev"],
    "China": [
        "Aeroporto Internacional de Xangai Pudong",
        "Aeroporto Internacional de Pequim Capital"
    ],
    "Coreia do Norte": ["Aeroporto Internacional de Pyongyang Sunan"],
    "Coreia do Sul": ["Aeroporto Internacional de Incheon"],
    "Dinamarca": ["Aeroporto de Copenhague"],
    "Eslováquia": ["Aeroporto de Bratislava"],
    "Eslovênia": ["Aeroporto de Ljubljana Joe Pu?nik"],
    "Espanha": [
        "Aeroporto Adolfo Suárez Madrid-Barajas",
        "Aeroporto de Barcelona-El Prat (Espanha)"
    ],
    "Estônia": ["Aeroporto de Tallinn"],
    "Estados Unidos": ["Aeroporto Internacional Hartsfield-Jackson Atlanta"],
    "Filipinas": ["Aeroporto Internacional Ninoy Aquino"],
    "Finlândia": ["Aeroporto de Helsinque"],
    "França": ["Aeroporto de Toulouse-Blagnac (França)"],
    "Hong Kong": ["Aeroporto Internacional de Hong Kong"],
    "Hungria": ["Aeroporto Internacional de Budapeste Ferenc Liszt"],
    "Ilhas Faroe": ["Aeroporto de Vágar"],
    "Índia": ["Aeroporto Internacional Indira Gandhi"],
    "Indonésia": [
        "Aeroporto Internacional Soekarno-Hatta (Jacarta)",
        "Aeroporto Internacional Ngurah Rai (Bali)"
    ],
    "Irlanda": ["Aeroporto de Dublin"],
    "Itália": [
        "Aeroporto de Roma-Fiumicino",
        "Aeroporto de Milão-Malpensa"
    ],
    "Japão": [
        "Aeroporto Internacional de Narita (Tóquio)",
        "Aeroporto Internacional de Haneda (Tóquio)",
        "Aeroporto Internacional de Kansai (Osaka)"
    ],
    "Laos": ["Aeroporto Internacional de Wattay (Vientiane)"],
    "Letônia": ["Aeroporto Internacional de Riga"],
    "Lituânia": ["Aeroporto Internacional de Vilnius"],
    "Luxemburgo": ["Aeroporto de Luxemburgo"],
    "Malásia": [
        "Aeroporto Internacional de Kuala Lumpur (Sepang)",
        "Aeroporto Internacional de Penang (Penang)"
    ],
    "Maldivas": ["Aeroporto Internacional de Malé"],
    "Malta": ["Aeroporto Internacional de Malta"],
    "Noruega": ["Aeroporto de Oslo-Gardermoen"],
    "Países Baixos (Holanda)": ["Aeroporto de Schiphol (Amsterdã)"],
    "Polônia": ["Aeroporto de Varsóvia Chopin"],
    "Portugal": [
        "Aeroporto Humberto Delgado (Lisboa)",
        "Aeroporto Francisco Sá Carneiro (Porto)"
    ],
    "Reino Unido": [
        "Aeroporto de Heathrow (Londres)",
        "Aeroporto de Gatwick (Londres)"
    ],
    "Tcheca, República": ["Aeroporto de Praga"],
    "Romênia": ["Aeroporto Internacional Henri Coand? (Bucareste)"],
    "Rússia": [
        "Aeroporto Internacional Sheremetyevo (Moscou)",
        "Aeroporto de Pulkovo (São Petersburgo)"
    ],
    "Sérvia": ["Aeroporto Nikola Tesla (Belgrado)"],
    "Singapura": ["Aeroporto Internacional de Changi"],
    "Suécia": ["Aeroporto de Estocolmo-Arlanda"],
    "Suíça": ["Aeroporto de Zurique"],
    "Tailândia": [
        "Aeroporto Internacional de Suvarnabhumi",
        "Aeroporto Internacional Don Mueang"
    ],
    "Taiwan (Formosa)": ["Aeroporto Internacional de Taiwan Taoyuan"],
    "Turquia": ["Aeroporto de Istambul"],
    "Ucrânia": ["Aeroporto Internacional de Boryspil (Kiev)"],
    "Vietnã": [
        "Aeroporto Internacional de Tan Son Nhat",
        "Aeroporto Internacional de Noi Bai"
    ]
}

In [46]:
aeroportos_nome = {
    "Aeroporto Internacional de Guarulhos": "SP-Guarulhos",
    "Aeroporto Internacional do Recife": "PE",
    "Aeroporto Internacional de Salvador": "BA",
    "Aeroporto Internacional de Natal": "RN",
    "Aeroporto Internacional de São Luís": "MA",
    "Aeroporto Internacional Pinto Martins": "CE",
    "Aeroporto Internacional de Nursultan Nazarbayev": "KAZ",
    "Aeroporto Internacional de Xangai Pudong": "CHN-Xangai",
    "Aeroporto Internacional de Pequim Capital": "CHN-Pequim",
    "Aeroporto Internacional de Pyongyang Sunan": "PRK",
    "Aeroporto Internacional de Incheon": "KOR",
    "Aeroporto Internacional Ninoy Aquino": "PHL",
    "Aeroporto Internacional de Hong Kong": "HKG",
    "Aeroporto Internacional Indira Gandhi": "IND-Delhi",
    "Aeroporto Internacional Soekarno-Hatta (Jacarta)": "IDN-Jakarta",
    "Aeroporto Internacional Ngurah Rai (Bali)": "IDN-Bali",
    "Aeroporto Internacional de Narita (Tóquio)": "JPN-Narita",
    "Aeroporto Internacional de Haneda (Tóquio)": "JPN-Haneda",
    "Aeroporto Internacional de Kansai (Osaka)": "JPN-Kansai",
    "Aeroporto Internacional de Wattay (Vientiane)": "LAO",
    "Aeroporto Internacional de Kuala Lumpur (Sepang)": "MYS",
    "Aeroporto Internacional de Penang (Penang)": "MYS-Penang",
    "Aeroporto Internacional de Malé": "MDV",
    "Aeroporto Internacional de Changi": "SGP",
    "Aeroporto Internacional de Suvarnabhumi": "THA-Bangkok",
    "Aeroporto Internacional Don Mueang": "THA-DonMueang",
    "Aeroporto Internacional de Taiwan Taoyuan": "TWN",
    "Aeroporto Internacional de Tan Son Nhat": "VNM-HoChiMinh",
    "Aeroporto Internacional de Noi Bai": "VNM-Hanoi",
    "Aeroporto de Frankfurt": "DEU-Frankfurt",
    "Aeroporto de Dublin": "IRL",
    "Aeroporto de Varsóvia Chopin": "POL",
    "Aeroporto de Oslo-Gardermoen": "NOR",
    "Aeroporto de Roma-Fiumicino": "ITA-Roma",
    "Aeroporto de Milão-Malpensa": "ITA-Milao",
    "Aeroporto de Praga": "CZE",
    "Aeroporto de Heathrow (Londres)": "GBR-Heathrow",
    "Aeroporto de Gatwick (Londres)": "GBR-Gatwick",
    "Aeroporto Internacional de Budapeste Ferenc Liszt": "HUN",
    "Aeroporto de Schiphol (Amsterdã)": "NLD",
    "Aeroporto Internacional de Boryspil (Kiev)": "UKR",
    "Aeroporto de Istambul": "TUR",
    "Aeroporto de Zurique": "CHE",
    "Aeroporto de Estocolmo-Arlanda": "SWE",
    "Aeroporto Nikola Tesla (Belgrado)": "SRB",
    "Aeroporto Internacional Sheremetyevo (Moscou)": "RUS-Moscou",
    "Aeroporto de Pulkovo (São Petersburgo)": "RUS-SPetersburgo",
    "Aeroporto Internacional Henri Coand? (Bucareste)": "ROU",
    "Aeroporto Humberto Delgado (Lisboa)": "PRT-Lisboa",
    "Aeroporto Francisco Sá Carneiro (Porto)": "PRT-Porto",
    "Aeroporto Internacional de Malta": "MLT",
    "Aeroporto de Luxemburgo": "LUX",
    "Aeroporto Internacional de Vilnius": "LTU",
    "Aeroporto Internacional de Riga": "LVA",
    "Aeroporto Internacional Madre Teresa (Tirana)": "ALB",
    "Aeroporto de Barcelona-El Prat (Espanha)": "ESP-Barcelona",
    "Aeroporto de Toulouse-Blagnac (França)": "FRA-Toulouse",
    "Aeroporto Internacional de Viena": "AUT",
    "Aeroporto de Bruxelas": "BEL",
    "Aeroporto de Sófia": "BGR",
    "Aeroporto de Bratislava": "SVK",
    "Aeroporto de Ljubljana Joe Pu?nik": "SVN",
    "Aeroporto Adolfo Suárez Madrid-Barajas": "ESP-Madrid",
    "Aeroporto de Barcelona-El Prat": "ESP-Barcelona",
    "Aeroporto de Tallinn": "EST",
    "Aeroporto de Vágar": "FRO",
    "Aeroporto de Helsinque": "FIN",
    "Aeroporto Internacional de Brasília": "DF",
    "Aeroporto Internacional de Várzea Grande": "MT",
    "Aeroporto Internacional de Belém": "PA",
    "Aeroporto Internacional de Tabatinga": "AM-Tabatinga",
    "Aeroporto Internacional de Manaus": "AM-Manaus",
    "Aeroporto Internacional de Macapá": "AP",
    "Aeroporto Internacional de Fortaleza": "CE",
    "Aeroporto Internacional de Maceió": "AL",
    "Aeroporto Internacional de Aracaju": "SE",
    "Aeroporto Internacional de Belo Horizonte": "MG",
    "Aeroporto Santos Dumont": "RJ-SantosDumont",
    "Aeroporto Internacional do Rio de Janeiro": "RJ-Galeão",
    "Aeroporto Internacional de Vitória": "ES",
    "Aeroporto Internacional de São José dos Campos": "SP-SJC",
    "Aeroporto Internacional de Viracopos": "SP-Viracopos",
    "Aeroporto Internacional de Curitiba": "PR",
    "Aeroporto Internacional de Florianópolis": "SC-Florianopolis",
    "Aeroporto Internacional de Navegantes": "SC-Navegantes",
    "Aeroporto Internacional de Porto Alegre": "RS",
    "Aeroporto de Copenhague": "DNK",
    "Aeroporto Internacional Hartsfield-Jackson Atlanta": "USA-Atlanta",
    "Aeroporto de Teresina": "PI",
    "Aeroporto Internacional de João Pessoa": "PB"
}

In [47]:
# Dicionário para armazenar as rotas por estado
aeroportos_rotas = {}

# Preenche o dicionário com as rotas de cada estado
for i in lista_estados:
    df_aux = df_nordeste.loc[df_nordeste['UF do Produto'] == i]
    u = df_aux['Países'].unique()
    paises = u.tolist()
    aeroporto = []
    for j in paises:
        if j in aeroportos_exterior.keys():
            for k in aeroportos_exterior[j]:
                aeroporto.append(k)
    aeroportos_rotas[i] = aeroporto


aeroportos_rotas['Piauí']

['Aeroporto Internacional de Viena',
 'Aeroporto de Frankfurt',
 'Aeroporto Internacional de Xangai Pudong',
 'Aeroporto Internacional de Pequim Capital']

In [48]:
dados = []  # Lista para armazenar os dados estruturados

for estado in lista_estados:
    df_aux = df_nordeste.loc[df_nordeste['UF do Produto'] == estado]
    
    for _, linha in df_aux.iterrows():
        aeroporto_nacional = linha['URF']
        origem = linha['Países']
        
        if origem in aeroportos_exterior.keys():
            for aeroporto_internacional in aeroportos_exterior[origem]:
                dados.append({
                    "Estado": estado,
                    "Aeroporto": aeroporto_nacional,
                    "Origem": aeroporto_internacional
                })

# Criar o DataFrame a partir da lista de dicionários
rotas_originais = pd.DataFrame(dados)
rotas_originais

,Estado,Aeroporto,Origem
0,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional Hartsfield-Jackson Atl...
1,Alagoas,Aeroporto Internacional do Recife,Aeroporto Internacional Hartsfield-Jackson Atl...
2,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Xangai Pudong
3,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Pequim Capital
4,Alagoas,Aeroporto Internacional do Recife,Aeroporto de Praga
...,...,...,...
428,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Viena
429,Rio Grande do Norte,Aeroporto Internacional do Recife,Aeroporto de Frankfurt
430,Rio Grande do Norte,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Viena
431,Sergipe,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Xangai Pudong
432,Sergipe,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Pequim Capital

In [49]:
def best_route(alvo,regional):
    for i in regional:
        aux = df[(df['InputID'] == alvo) & (df['TargetID'] == i)]['Distância km'].values[0]
        min = 0
        if min == 0 or aux < min:
            melhor = i
            min = aux
    
    return melhor

def create_table(tabela, edges,internacional,regional,estado,df):
    for i in edges:
        aux = {'Destino' : estado}
        if i[0] in internacional:
            if i[1] in regional:
                distancia = df[(df['InputID'] == i[0]) & (df['TargetID'] == i[1])]['Distância km'].values[0]
                aux.update({
                    'Origem' : i[0],
                    'Intermerdiario' : '*',
                    'Final' : i[1],
                    'Distancia' : distancia,
                    'Emissão de CO2' : round((((distancia * 1.652) * 3.15/1000)),2)})
                tabela.append(aux) 
            else:
                target = best_route(i[1],regional)
                distancia = df[(df['InputID'] == i[0]) & (df['TargetID'] == i[1])]['Distância km'].values[0] + df[(df['InputID'] == target) & (df['TargetID'] == i[1])]['Distância km'].values[0]
                aux.update({
                    'Origem' : i[0],
                    'Intermerdiario' : i[1],
                    'Final' : target,
                    'Distancia' : distancia,
                    'Emissão de CO2' : round((((distancia * 1.652) * 3.15)/1000),2)
                    },)
                tabela.append(aux) 
    return tabela

In [50]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Função para calcular distâncias entre aeroportos
def achar_distancias(lista_nacionais, lista_interesse, df):
    df_filtrado = df[
        (df['InputID'].isin(lista_nacionais)) &
        (df['TargetID'].isin(lista_interesse))
    ]
    distancias = {}
    for nacional in lista_nacionais:
        distancias[nacional] = {}
        for interesse in lista_interesse:
            distancia = df_filtrado[
                (df_filtrado['InputID'] == nacional) & 
                (df_filtrado['TargetID'] == interesse)
            ]['Distância km']
            distancias[nacional][interesse] = distancia.values[0] if not distancia.empty else 0
    return distancias

# Função para carregar o grafo a partir do DataFrame
def load_graph_from_df(df, rotas, source_airports, interest_airports, local_airport):
    distancia = achar_distancias(interest_airports, local_airport, df)

    G = nx.DiGraph()
    for _, linha in rotas.iterrows():
        source = linha['Origem']
        target = linha['Aeroporto']
        df_filtrado = df[(df['InputID'] == source) & (df['TargetID'] == target)]

        if not df_filtrado.empty:
            d = df_filtrado['Distância km'].values[0]
            # Soma com a menor distância adicional do aeroporto de interesse até um local
            d2 = min([distancia.get(target, {}).get(local, 0) or 0 for local in local_airport]) if local_airport else 0
            d_total = d + d2
            weight = ((d_total * 1.652) * 3.15)/1000

            G.add_edge(source, target, weight=weight)

    for airport in interest_airports:
        for local in local_airport:
            if not G.has_edge(airport, local):
                d = distancia.get(airport, {}).get(local, 0) or 0
                weight = ((d * 1.652) * 3.15)/1000
                G.add_edge(airport, local, weight=weight)

    return G


# Função para destacar as rotas ideais
def highlight_routes(G, international_airports, national_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path_to_regional = None
            for regional_airport in regional_airports:
                if regional_airport not in G:
                    continue
                for national_airport in national_airports:
                    if national_airport not in G:
                        continue
                    try:
                        path_to_national = nx.shortest_path(G, source=intl_airport, target=national_airport, weight='weight')
                        weight_to_national = nx.path_weight(G, path_to_national, weight='weight')
                        path_to_regional = nx.shortest_path(G, source=national_airport, target=regional_airport, weight='weight')
                        weight_to_regional = nx.path_weight(G, path_to_regional, weight='weight')
                        total_weight = weight_to_national + weight_to_regional
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path_to_regional = path_to_national + path_to_regional[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path_to_regional:
                for i in range(len(best_path_to_regional) - 1):
                    edge = (best_path_to_regional[i], best_path_to_regional[i + 1])
                    ideal_path_edges.add(edge)
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)

def plot_clean_graph(G, ideal_path_edges, interest_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    # Define as cores dos nós
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }
    
    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in interest_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')
    
    edge_labels = nx.get_edge_attributes(G, 'weight')
    labels = {edge: f"{round(weight, 2)}" for edge, weight in edge_labels.items()}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_size=8, font_color='red')
    
    plt.title(f'{title_suffix}')
    plt.axis('off')
    
    # Adiciona legenda manualmente
    legend_labels = {
        "Destino": 'orange',
        "Nacional": 'lightgreen',
        "Internacional": 'lightblue'
    }
    
    for label, color in legend_labels.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)
    
    plt.savefig(save_path)  # Salva o gráfico
    plt.close()  # Fecha a figura para liberar memória


tabela_rotas = []
# Loop para processar aeroportos em lotes
for i in aeroportos_nordeste.keys():
    batch_size = 4
    for j in range(0, len(aeroportos_rotas[i]), batch_size):
        subset_origem = aeroportos_rotas[i][j:j + batch_size]
        rotas = rotas_originais[
            (rotas_originais['Estado'] == i) & 
            (rotas_originais['Origem'].isin(subset_origem))
        ]
        aeroportos_intermediarios = []
        for _, linha in rotas.iterrows():
            aeroportos_intermediarios.append(linha['Aeroporto'])

        G = load_graph_from_df(df, rotas, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])        
        tabela_rotas = create_table(tabela_rotas,ideal_path_edges,subset_origem, aeroportos_estado[i],i,df)
        save_path = f"rota_original/{i}_{j//batch_size + 1}.png"  # Define o caminho para salvar o gráfico
        plot_clean_graph(G, ideal_path_edges, aeroportos_intermediarios, aeroportos_estado[i], title_suffix=f"{i}", save_path=save_path)

In [51]:
tabela_rotas = pd.DataFrame(tabela_rotas)

# Exporta o DataFrame ordenado para um arquivo CSV
tabela_rotas.to_csv('./rota_proposta/Tabela_Rotas_Originais.csv', index=False)

tabela_rotas

,Destino,Origem,Intermerdiario,Final,Distancia,Emissão de CO2
0,Alagoas,Aeroporto Internacional Hartsfield-Jackson Atl...,Aeroporto Internacional do Recife,Aeroporto Internacional de Maceió,7111,37.00
1,Alagoas,Aeroporto de Praga,Aeroporto Internacional do Recife,Aeroporto Internacional de Maceió,8143,42.37
2,Alagoas,Aeroporto Internacional de Pequim Capital,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Maceió,19539,101.68
3,Alagoas,Aeroporto Internacional de Xangai Pudong,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Maceió,20542,106.90
4,Alagoas,Aeroporto de Frankfurt,Aeroporto Internacional do Recife,Aeroporto Internacional de Maceió,7829,40.74
...,...,...,...,...,...,...
106,Rio Grande do Norte,Aeroporto Internacional de Penang (Penang),Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,15339,79.82
107,Rio Grande do Norte,Aeroporto de Milão-Malpensa,Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,7634,39.73
108,Rio Grande do Norte,Aeroporto de Zurique,Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,7760,40.38
109,Sergipe,Aeroporto Internacional de Xangai Pudong,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Aracaju,20286,105.56
110,Sergipe,Aeroporto Internacional de Pequim Capital,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Aracaju,19283,100.34

# Grafo - Rota Proposta

In [52]:
aeroportos_Hub = ["Aeroporto Internacional de Maceió",
                  "Aeroporto Internacional de Salvador",
                  "Aeroporto Internacional de Fortaleza",
                  "Aeroporto Internacional de São Luís",
                  "Aeroporto Internacional do Recife",
                  "Aeroporto Internacional de Natal",
                  "Aeroporto Internacional de Aracaju",
                  "Aeroporto Internacional de João Pessoa",
                  "Aeroporto de Teresina"]

In [53]:
aeroportos_nordeste.keys()

dict_keys(['Alagoas', 'Bahia', 'Ceará', 'Maranhão', 'Paraíba', 'Pernambuco', 'Piauí', 'Rio Grande do Norte', 'Sergipe'])

In [54]:
dados = []  # Lista para armazenar os dados estruturados

for estado in aeroportos_nordeste.keys():
    df_aux = df_nordeste.loc[df_nordeste['UF do Produto'] == estado]
    
    for _, linha in df_aux.iterrows():
        for i in aeroportos_Hub:
            aeroporto_nacional = i
            origem = linha['Países']
            if origem in aeroportos_exterior.keys():
                for aeroporto_internacional in aeroportos_exterior[origem]:
                    dados.append({
                        "Estado": estado,
                        "Aeroporto": aeroporto_nacional,
                        "Origem": aeroporto_internacional
                    })

# Criar o DataFrame a partir da lista de dicionários
rotas_originais = pd.DataFrame(dados)
rotas_originais

,Estado,Aeroporto,Origem
0,Alagoas,Aeroporto Internacional de Maceió,Aeroporto Internacional Hartsfield-Jackson Atl...
1,Alagoas,Aeroporto Internacional de Salvador,Aeroporto Internacional Hartsfield-Jackson Atl...
2,Alagoas,Aeroporto Internacional de Fortaleza,Aeroporto Internacional Hartsfield-Jackson Atl...
3,Alagoas,Aeroporto Internacional de São Luís,Aeroporto Internacional Hartsfield-Jackson Atl...
4,Alagoas,Aeroporto Internacional do Recife,Aeroporto Internacional Hartsfield-Jackson Atl...
...,...,...,...
3892,Sergipe,Aeroporto Internacional de Aracaju,Aeroporto Internacional de Pequim Capital
3893,Sergipe,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Xangai Pudong
3894,Sergipe,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Pequim Capital
3895,Sergipe,Aeroporto de Teresina,Aeroporto Internacional de Xangai Pudong
3896,Sergipe,Aeroporto de Teresina,Aeroporto Internacional de Pequim Capital

In [55]:
# -----------------------------
def load_graph_from_df(df, rotas, local_airport):

    G = nx.DiGraph()

    for _, linha in rotas.iterrows():
        source = linha['Origem']


        for i in local_airport:
            df_filtrado = df[(df['InputID'] == source) & (df['TargetID'] == i)]
            if not df_filtrado.empty:
                d = df_filtrado['Distância km'].values[0]
                weight = ((d * 1.652) * 3.15)/1000

                G.add_edge(source, i, weight=weight)

    return G

# -----------------------------
# Encontra caminhos ideais passando por hubs
def highlight_routes(G, international_airports, hub_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path = None
            for hub in hub_airports:
                if hub not in G:
                    continue
                for destino in regional_airports:
                    if destino not in G:
                        continue
                    try:
                        path1 = nx.shortest_path(G, source=intl_airport, target=hub, weight='weight')
                        w1 = nx.path_weight(G, path1, weight='weight')
                        path2 = nx.shortest_path(G, source=hub, target=destino, weight='weight')
                        w2 = nx.path_weight(G, path2, weight='weight')
                        total_weight = w1 + w2
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path = path1 + path2[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path:
                for i in range(len(best_path) - 1):
                    ideal_path_edges.add((best_path[i], best_path[i + 1]))
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)

# -----------------------------
# Função para desenhar e salvar o grafo
def plot_clean_graph(G, ideal_path_edges, hub_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }

    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in hub_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')

    edge_labels = nx.get_edge_attributes(G, 'weight')
    labels = {edge: f"{round(weight, 2)}" for edge, weight in edge_labels.items()}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_size=8, font_color='red')

    plt.title(f'{title_suffix}')
    plt.axis('off')
    for label, color in node_colors.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)

    plt.savefig(save_path)
    plt.close()

# -----------------------------
# Loop principal com rotas via Hubs
tabela_proposta = []

for estado in aeroportos_nordeste.keys():
    batch_size = 13
    for j in range(0, len(aeroportos_rotas[estado]), batch_size):
        subset_origem = aeroportos_rotas[estado][j:j + batch_size]
        
        rotas = rotas_originais[
            (rotas_originais['Estado'] == estado) & 
            (rotas_originais['Origem'].isin(subset_origem))
        ]

        aeroportos_destino = aeroportos_estado[estado]

        G = load_graph_from_df(df, rotas, aeroportos_destino)
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_Hub, aeroportos_destino)

        tabela_proposta = create_table(tabela_proposta, ideal_path_edges, subset_origem, aeroportos_destino, estado, df)

        save_path = f"rota_proposta/{estado}_{j//batch_size + 1}.png"
        plot_clean_graph(G, ideal_path_edges, aeroportos_Hub, aeroportos_destino, title_suffix=f"{estado}", save_path=save_path)

In [56]:
tabela_proposta = pd.DataFrame(tabela_proposta)

# Exporta o DataFrame ordenado para um arquivo CSV
tabela_proposta.to_csv('./rota_proposta/Tabela_Rotas_Propostas.csv', index=False)
tabela_proposta

,Destino,Origem,Intermerdiario,Final,Distancia,Emissão de CO2
0,Alagoas,Aeroporto Internacional Hartsfield-Jackson Atl...,*,Aeroporto Internacional de Maceió,6983,36.34
1,Alagoas,Aeroporto de Praga,*,Aeroporto Internacional de Maceió,8141,42.36
2,Alagoas,Aeroporto de Frankfurt,*,Aeroporto Internacional de Maceió,7825,40.72
3,Alagoas,Aeroporto Internacional de Pequim Capital,*,Aeroporto Internacional de Maceió,15617,81.27
4,Alagoas,Aeroporto Internacional de Xangai Pudong,*,Aeroporto Internacional de Maceió,16641,86.60
...,...,...,...,...,...,...
106,Rio Grande do Norte,Aeroporto Internacional Hartsfield-Jackson Atl...,*,Aeroporto Internacional de Natal,6768,35.22
107,Rio Grande do Norte,Aeroporto de Roma-Fiumicino,*,Aeroporto Internacional de Natal,7136,37.13
108,Rio Grande do Norte,Aeroporto Internacional de Penang (Penang),*,Aeroporto Internacional de Natal,15111,78.63
109,Sergipe,Aeroporto Internacional de Pequim Capital,*,Aeroporto Internacional de Aracaju,15873,82.60
110,Sergipe,Aeroporto Internacional de Xangai Pudong,*,Aeroporto Internacional de Aracaju,16896,87.92

# Tabela Comparativa

In [57]:
import pandas as pd

# Convertendo listas de dicionários em DataFrames
tabela_rota = pd.DataFrame(tabela_rotas)
tabela_proposta = pd.DataFrame(tabela_proposta)

# Função para criar a tabela comparativa
def criar_tabela_comparativa(tabela_rotas, tabela_hub):
    # Renomeando colunas da tabela de rotas para padronizar
    tabela_comparativa = tabela_rotas[['Destino', 'Origem', 'Distancia', 'Emissão de CO2']].copy()
    tabela_comparativa.rename(columns={
        'Destino': 'Estado',
        'Distancia': f'Distância original',
        'Emissão de CO2': f'Emissão original'
    }, inplace=True)

    # Agrupando a tabela_hub por 'Destino' (estado) e 'Origem' para calcular as médias
    tabela_hub_agrupada = tabela_hub.groupby(['Destino', 'Origem'], as_index=False).agg({
        'Distancia': 'mean',
        'Emissão de CO2': 'mean'
    })

    # Mesclando as informações agregadas na tabela comparativa
    tabela_comparativa = tabela_comparativa.merge(
        tabela_hub_agrupada.rename(columns={
            'Destino': 'Estado',
            'Distancia': f'Distância hub',
            'Emissão de CO2': f'Emissão hub'
        }),
        on=['Estado', 'Origem'],
        how='left'
    )

    return tabela_comparativa

# Criando as tabelas comparativas separadas
tabela_comparativa = criar_tabela_comparativa(tabela_rota, tabela_proposta)


# Salvando a tabela comparativa geral
tabela_comparativa.to_csv('./rota_proposta/Tabela_Comparativa.csv', index=False)

# Criando e salvando tabelas específicas
tabela_distancia = tabela_comparativa[['Origem', 'Estado', 'Distância hub', 'Distância original']]
tabela_emissao = tabela_comparativa[['Origem', 'Estado', 'Emissão hub', 'Emissão original']]

# Salvando os arquivos CSV separados
tabela_distancia.to_csv('./rota_proposta/Tabela_Distancia.csv', index=False)
tabela_emissao.to_csv('./rota_proposta/Tabela_Emissao.csv', index=False)

# Exibindo como verificação
tabela_comparativa

,Estado,Origem,Distância original,Emissão original,Distância hub,Emissão hub
0,Alagoas,Aeroporto Internacional Hartsfield-Jackson Atl...,7111,37.00,6983.0,36.34
1,Alagoas,Aeroporto de Praga,8143,42.37,8141.0,42.36
2,Alagoas,Aeroporto Internacional de Pequim Capital,19539,101.68,15617.0,81.27
3,Alagoas,Aeroporto Internacional de Xangai Pudong,20542,106.90,16641.0,86.60
4,Alagoas,Aeroporto de Frankfurt,7829,40.74,7825.0,40.72
...,...,...,...,...,...,...
106,Rio Grande do Norte,Aeroporto Internacional de Penang (Penang),15339,79.82,15111.0,78.63
107,Rio Grande do Norte,Aeroporto de Milão-Malpensa,7634,39.73,7171.0,37.32
108,Rio Grande do Norte,Aeroporto de Zurique,7760,40.38,7293.0,37.95
109,Sergipe,Aeroporto Internacional de Xangai Pudong,20286,105.56,16896.0,87.92
110,Sergipe,Aeroporto Internacional de Pequim Capital,19283,100.34,15873.0,82.60

In [58]:
import pandas as pd

# Função para análise comparativa por estado
def analisar_por_estado(tabela_comparativa, metrica):
    """
    Analisa qual rota (original ou via hub) é melhor para cada estado com base na métrica fornecida.

    Parâmetros:
        tabela_comparativa (pd.DataFrame): Tabela contendo as distâncias ou emissões de CO2.
        tipo (str): 'carga' ou 'comercial', para diferenciar os tipos de transporte.
        metrica (str): 'Distância' ou 'Emissão', para definir a métrica de comparação.

    Retorna:
        analise (pd.DataFrame): DataFrame com a contagem de casos por estado.
        conclusao (str): Conclusão geral sobre qual rota é melhor.
    """

    col_original = f'{metrica} original'
    col_hub = f'{metrica} hub'

    # Verifica se as colunas necessárias existem na tabela
    if col_original not in tabela_comparativa.columns or col_hub not in tabela_comparativa.columns:
        raise ValueError(f"As colunas esperadas '{col_original}' e '{col_hub}' não foram encontradas na tabela.")

    # Garantindo que não haja NaN nos cálculos, usando .loc[:] para evitar SettingWithCopyWarning
    tabela_comparativa = tabela_comparativa.copy()  # Garante que estamos trabalhando com uma cópia
    tabela_comparativa.loc[:, col_original] = tabela_comparativa[col_original].fillna(float('inf'))
    tabela_comparativa.loc[:, col_hub] = tabela_comparativa[col_hub].fillna(float('inf'))

    # Agrupando por Estado e aplicando a análise sem incluir as colunas de agrupamento na função apply()
    analise = tabela_comparativa.groupby('Estado', as_index=False)[[col_original, col_hub]].apply(
        lambda x: pd.Series({
            'iguais': (x[col_original] == x[col_hub]).sum(),
            'hub_menor': (x[col_hub] < x[col_original]).sum(),
            'original_menor': (x[col_original] < x[col_hub]).sum()
        })
    )

    # Determinando a melhor rota para cada estado
    analise['Melhor rota'] = analise.apply(
        lambda x: 'Original' if x['original_menor'] >= x['hub_menor'] else 'Proposta',
        axis=1
    )

    # Determinando qual rota é melhor no geral
    total_original_menor = analise['original_menor'].sum()
    total_hub_menor = analise['hub_menor'].sum()

    conclusao = f"\nConclusão geral ({metrica}): " + (
        "A rota original é melhor." if total_original_menor >= total_hub_menor else "A rota via hub é melhor."
    )

    return analise, conclusao


# Executando a análise para cada caso
analise_emissao, conclusao_emissao = analisar_por_estado(tabela_emissao, "Emissão")

In [59]:
print(analise_emissao)
print(conclusao_emissao)

                Estado  iguais  hub_menor  original_menor Melhor rota
0              Alagoas       0          5               0    Proposta
1                Bahia      21          9               0    Proposta
2                Ceará      15          3               0    Proposta
3             Maranhão       0          7               0    Proposta
4              Paraíba       0         15               0    Proposta
5           Pernambuco      14          4               0    Proposta
6                Piauí       0          4               0    Proposta
7  Rio Grande do Norte       3          9               0    Proposta
8              Sergipe       0          2               0    Proposta

Conclusão geral (Emissão): A rota via hub é melhor.