In [177]:
pip install pandas

Requirement already satisfied: pandas in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\Alice\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [178]:
pip install scipy

Requirement already satisfied: scipy in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.14.1)
Requirement already satisfied: numpy<2.3,>=1.23.5 in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scipy) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\Alice\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# Preparação dos dados

In [179]:
# Importação da biblioteca pandas para manipulação de dados
import pandas as pd

# Caminhos para os arquivos CSV
file_path = './csv_recebidos/Distâncias_aeroportos.csv'  # Arquivo com as distâncias entre aeroportos
file_path1 = './csv_recebidos/Nome_Aeroporto.csv'  # Arquivo com os nomes dos aeroportos

# Carrega os arquivos CSV em DataFrames
df = pd.read_csv(file_path)  # DataFrame com as distâncias
df_nome = pd.read_csv(file_path1)  # DataFrame com os nomes dos aeroportos

df

      InputID  TargetID  Distance (km)
0          91         1           2183
1          91         2            108
2          91         3            737
3          91         4            155
4          91         5           1145
...       ...       ...            ...
8185        1        87           1233
8186        1        88           9327
8187        1        89           7487
8188        1        90           2070
8189        1        91           2183

[8190 rows x 3 columns]

In [180]:
# Renomeia as colunas do DataFrame de distâncias
df.columns = ["InputID", "TargetID", "Distância km"]
df

      InputID  TargetID  Distância km
0          91         1          2183
1          91         2           108
2          91         3           737
3          91         4           155
4          91         5          1145
...       ...       ...           ...
8185        1        87          1233
8186        1        88          9327
8187        1        89          7487
8188        1        90          2070
8189        1        91          2183

[8190 rows x 3 columns]

In [181]:
# Cria um mapeamento de IDs para nomes dos aeroportos
mapa_ids = {i+1: nome for i, nome in enumerate(df_nome['Aeroporto'])}

# Substitui os IDs nas colunas 'InputID' e 'TargetID' pelos nomes dos aeroportos
df['InputID'] = df['InputID'].replace(mapa_ids)
df['TargetID'] = df['TargetID'].replace(mapa_ids)
# Adiciona uma coluna de emissão de CO2 com base na distância

df

,InputID,TargetID,Distância km
0,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Guarulhos,2183
1,Aeroporto Internacional de João Pessoa,Aeroporto Internacional do Recife,108
2,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Salvador,737
3,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de Natal,155
4,Aeroporto Internacional de João Pessoa,Aeroporto Internacional de São Luís,1145
...,...,...,...
8185,Aeroporto Internacional de Guarulhos,Aeroporto Jorge Amado,1233
8186,Aeroporto Internacional de Guarulhos,Aeroporto de Copenhague,9327
8187,Aeroporto Internacional de Guarulhos,Aeroporto Internacional Hartsfield-Jackson Atl...,7487
8188,Aeroporto Internacional de Guarulhos,Aeroporto de Teresina,2070
8189,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de João Pessoa,2183

In [182]:
# Função para formatar horas no formato HH:MM
def format_time(hours):
    h = int(hours)
    m = int((hours - h) * 60)
    return f"{h:02}:{m:02}"

# Calcula o tempo médio de voo para aeronaves comerciais
df['Tempo Médio Horas - Comercial'] = df['Distância km'].apply(
    lambda d: f"{format_time(d / 900)} ~ {format_time(d / 850)}"
)

# Calcula o tempo médio de voo para aeronaves cargueiras
df['Tempo Médio Horas - Cargueiro'] = df['Distância km'].apply(
    lambda d: f"{format_time(d / 850)} ~ {format_time(d / 800)}"
)

df.to_csv('./csv_gerado/AAAAA.csv', index=False)

In [183]:
# Lista de aeroportos de interesse
aeroportos_interesse = [
    "Aeroporto Internacional de Guarulhos",
    "Aeroporto Internacional do Recife",
    "Aeroporto Internacional de Salvador",
    "Aeroporto Internacional de Natal",
    "Aeroporto Internacional de São Luís",
    "Aeroporto Internacional de Fortaleza",
    "Aeroporto Internacional de Brasília",
    "Aeroporto Internacional de Várzea Grande",
    "Aeroporto Internacional de Belém",
    "Aeroporto Internacional de Tabatinga",
    "Aeroporto Internacional de Manaus",
    "Aeroporto Internacional de Macapá",
    "Aeroporto Internacional de Maceió",
    "Aeroporto Internacional de Aracaju",
    "Aeroporto Internacional de Belo Horizonte",
    "Aeroporto Santos Dumont",
    "Aeroporto Internacional do Rio de Janeiro",
    "Aeroporto Internacional de Vitória",
    "Aeroporto Internacional de São José dos Campos",
    "Aeroporto Internacional de Viracopos",
    "Aeroporto Internacional de Curitiba",
    "Aeroporto Internacional de Florianópolis",
    "Aeroporto Internacional de Navegantes",
    "Aeroporto Internacional de Porto Alegre",
    "Aeroporto Internacional de Boa Vista"
]

# Gera uma lista de aeroportos de origem únicos
lista_origem = df['InputID'].unique().tolist()

# Remove os aeroportos de interesse da lista de origem
for i in aeroportos_interesse:
    try:
        lista_origem.remove(i)
    except ValueError:
        pass

lista_origem

['Aeroporto Internacional de João Pessoa',
 'Aeroporto de Teresina',
 'Aeroporto Internacional Hartsfield-Jackson Atlanta',
 'Aeroporto de Copenhague',
 'Aeroporto Jorge Amado',
 'Aeroporto de Helsinque',
 'Aeroporto de Vágar',
 'Aeroporto de Tallinn',
 'Aeroporto de Barcelona-El Prat',
 'Aeroporto Adolfo Suárez Madrid-Barajas',
 'Aeroporto de Ljubljana Jo\x9ee Pu?nik',
 'Aeroporto de Bratislava',
 'Aeroporto de Sófia',
 'Aeroporto de Bruxelas',
 'Aeroporto Internacional de Viena',
 'Aeroporto de Toulouse-Blagnac (França)',
 'Aeroporto de Barcelona-El Prat (Espanha)',
 'Aeroporto Internacional Madre Teresa (Tirana)',
 'Aeroporto Internacional de Riga',
 'Aeroporto Internacional de Vilnius',
 'Aeroporto de Luxemburgo',
 'Aeroporto Internacional de Malta',
 'Aeroporto Francisco Sá Carneiro (Porto)',
 'Aeroporto Humberto Delgado (Lisboa)',
 'Aeroporto Internacional Henri Coand? (Bucareste)',
 'Aeroporto de Pulkovo (São Petersburgo)',
 'Aeroporto Internacional Sheremetyevo (Moscou)',
 'Aeroporto Nikola Tesla (Belgrado)',
 'Aeroporto de Estocolmo-Arlanda',
 'Aeroporto de Zurique',
 'Aeroporto de Istambul',
 'Aeroporto Internacional de Boryspil (Kiev)',
 'Aeroporto de Schiphol (Amsterdã)',
 'Aeroporto Internacional de Budapeste Ferenc Liszt',
 'Aeroporto de Gatwick (Londres)',
 'Aeroporto de Heathrow (Londres)',
 'Aeroporto de Praga',
 'Aeroporto de Milão-Malpensa',
 'Aeroporto de Roma-Fiumicino',
 'Aeroporto de Oslo-Gardermoen',
 'Aeroporto de Varsóvia Chopin',
 'Aeroporto de Dublin',
 'Aeroporto de Frankfurt',
 'Aeroporto Internacional de Noi Bai',
 'Aeroporto Internacional de Tan Son Nhat',
 'Aeroporto Internacional de Taiwan Taoyuan',
 'Aeroporto Internacional Don Mueang',
 'Aeroporto Internacional de Suvarnabhumi',
 'Aeroporto Internacional de Changi',
 'Aeroporto Internacional de Malé',
 'Aeroporto Internacional de Penang (Penang)',
 'Aeroporto Internacional de Kuala Lumpur (Sepang)',
 'Aeroporto Internacional de Wattay (Vientiane)',
 'Aeroporto Internacional de Kansai (Osaka)',
 'Aeroporto Internacional de Haneda (Tóquio)',
 'Aeroporto Internacional de Narita (Tóquio)',
 'Aeroporto Internacional Ngurah Rai (Bali)',
 'Aeroporto Internacional Soekarno-Hatta (Jacarta)',
 'Aeroporto Internacional Indira Gandhi',
 'Aeroporto Internacional de Hong Kong',
 'Aeroporto Internacional Ninoy Aquino',
 'Aeroporto Internacional de Incheon',
 'Aeroporto Internacional de Pyongyang Sunan',
 'Aeroporto Internacional de Pequim Capital',
 'Aeroporto Internacional de Xangai Pudong',
 'Aeroporto Internacional de Nursultan Nazarbayev',
 'Aeroporto Internacional Pinto Martins']

In [184]:
aeroportos_estado = {"Alagoas": ["Aeroporto Internacional de Maceió"],
    "Bahia": ["Aeroporto Internacional de Salvador"],
    "Ilhéus": ["Aeroporto Jorge Amado"],
    "Ceará": ["Aeroporto Internacional de Fortaleza"],
    "Maranhão": ["Aeroporto Internacional de São Luís"],
    "Paraíba": ["Aeroporto Internacional de João Pessoa"],
    "Pernambuco": ["Aeroporto Internacional do Recife"],
    "Piauí": ["Aeroporto de Teresina"],
    "Rio Grande do Norte": ["Aeroporto Internacional de Natal"],
    "Sergipe": ["Aeroporto Internacional de Aracaju"]}

# Tabela completa

In [185]:
# Lista para armazenar os resultados
result = []

# Itera sobre todos os aeroportos de origem na lista_origem
for aeroporto_origem in lista_origem:
    # Inicializa um dicionário para armazenar os dados de cada aeroporto de destino
    dados_aeroportos = {estado_destino: [None, None, None] for estado_destino in aeroportos_estado.keys()}
    
    # Itera sobre os aeroportos de destino
    for estado_destino, aeroporto_destino in aeroportos_estado.items():
        # Seleciona a linha com informações sobre o aeroporto de origem e destino
        linha = df.loc[(df['InputID'] == aeroporto_origem) & (df['TargetID'] == aeroporto_destino[0])]
        
        if not linha.empty:  # Verifica se há dados para a combinação de aeroportos
            # Extrai os valores necessários da linha
            distancia = linha['Distância km'].values[0]
            tempo_comercial = linha['Tempo Médio Horas - Comercial'].values[0]
            tempo_carga = linha['Tempo Médio Horas - Cargueiro'].values[0]
            
            # Atualiza os dados do estado de destino
            dados_aeroportos[estado_destino] = [distancia, tempo_comercial, tempo_carga]

    # Prepara os dados para o aeroporto de origem atual
    dados_origem = {"Origem": aeroporto_origem}
    for estado_destino, valores in dados_aeroportos.items():
        dados_origem.update({
            f"{estado_destino} (Km)": valores[0],
            f"{estado_destino} (Hr - Comercial)": valores[1],
            f"{estado_destino} (Hr - Cargueiro)": valores[2],
        })
    
    # Adiciona os dados ao resultado
    result.append(dados_origem)

# Transforma o resultado em um DataFrame
df_result = pd.DataFrame(result)

df_result

,Origem,Alagoas (Km),Alagoas (Hr - Comercial),Alagoas (Hr - Cargueiro),Bahia (Km),Bahia (Hr - Comercial),Bahia (Hr - Cargueiro),Ilhéus (Km),Ilhéus (Hr - Comercial),Ilhéus (Hr - Cargueiro),...,Pernambuco (Hr - Cargueiro),Piauí (Km),Piauí (Hr - Comercial),Piauí (Hr - Cargueiro),Rio Grande do Norte (Km),Rio Grande do Norte (Hr - Comercial),Rio Grande do Norte (Hr - Cargueiro),Sergipe (Km),Sergipe (Hr - Comercial),Sergipe (Hr - Cargueiro)
0,Aeroporto Internacional de João Pessoa,227,00:15 ~ 00:16,00:16 ~ 00:17,737,00:49 ~ 00:52,00:52 ~ 00:55,958.0,01:03 ~ 01:07,01:07 ~ 01:11,...,00:07 ~ 00:08,902.0,01:00 ~ 01:03,01:03 ~ 01:07,155,00:10 ~ 00:10,00:10 ~ 00:11,480,00:32 ~ 00:33,00:33 ~ 00:36
1,Aeroporto de Teresina,898,00:59 ~ 01:03,01:03 ~ 01:07,999,01:06 ~ 01:10,01:10 ~ 01:14,1156.0,01:17 ~ 01:21,01:21 ~ 01:26,...,01:06 ~ 01:10,NaN,None,None,843,00:56 ~ 00:59,00:59 ~ 01:03,909,01:00 ~ 01:04,01:04 ~ 01:08
2,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,07:45 ~ 08:12,08:12 ~ 08:43,7099,07:53 ~ 08:21,08:21 ~ 08:52,7206.0,08:00 ~ 08:28,08:28 ~ 09:00,...,08:12 ~ 08:43,6124.0,06:48 ~ 07:12,07:12 ~ 07:39,6768,07:31 ~ 07:57,07:57 ~ 08:27,7032,07:48 ~ 08:16,08:16 ~ 08:47
3,Aeroporto de Copenhague,7479,08:18 ~ 08:47,08:47 ~ 09:20,7965,08:50 ~ 09:22,09:22 ~ 09:57,8188.0,09:05 ~ 09:37,09:37 ~ 10:14,...,08:39 ~ 09:11,7273.0,08:04 ~ 08:33,08:33 ~ 09:05,7116,07:54 ~ 08:22,08:22 ~ 08:53,7719,08:34 ~ 09:04,09:04 ~ 09:38
4,Aeroporto Jorge Amado,732,00:48 ~ 00:51,00:51 ~ 00:54,224,00:14 ~ 00:15,00:15 ~ 00:16,NaN,None,None,...,01:01 ~ 01:04,1156.0,01:17 ~ 01:21,01:21 ~ 01:26,1082,01:12 ~ 01:16,01:16 ~ 01:21,478,00:31 ~ 00:33,00:33 ~ 00:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Aeroporto Internacional de Pyongyang Sunan,16188,17:59 ~ 19:02,19:02 ~ 20:14,16696,18:33 ~ 19:38,19:38 ~ 20:52,16919.0,18:47 ~ 19:54,19:54 ~ 21:08,...,18:53 ~ 20:04,16048.0,17:49 ~ 18:52,18:52 ~ 20:03,15838,17:35 ~ 18:37,18:37 ~ 19:47,16441,18:16 ~ 19:20,19:20 ~ 20:33
63,Aeroporto Internacional de Pequim Capital,15617,17:21 ~ 18:22,18:22 ~ 19:31,16130,17:55 ~ 18:58,18:58 ~ 20:09,16347.0,18:09 ~ 19:13,19:13 ~ 20:26,...,18:12 ~ 19:21,15617.0,17:21 ~ 18:22,18:22 ~ 19:31,15285,16:59 ~ 17:58,17:58 ~ 19:06,15873,17:38 ~ 18:40,18:40 ~ 19:50
64,Aeroporto Internacional de Xangai Pudong,16641,18:29 ~ 19:34,19:34 ~ 20:48,17150,19:03 ~ 20:10,20:10 ~ 21:26,17357.0,19:17 ~ 20:25,20:25 ~ 21:41,...,19:25 ~ 20:37,16706.0,18:33 ~ 19:39,19:39 ~ 20:52,16326,18:08 ~ 19:12,19:12 ~ 20:24,16896,18:46 ~ 19:52,19:52 ~ 21:07
65,Aeroporto Internacional de Nursultan Nazarbayev,11988,13:19 ~ 14:06,14:06 ~ 14:59,12498,13:53 ~ 14:42,14:42 ~ 15:37,12708.0,14:07 ~ 14:57,14:57 ~ 15:53,...,13:56 ~ 14:48,12128.0,13:28 ~ 14:16,14:16 ~ 15:09,11673,12:58 ~ 13:43,13:43 ~ 14:35,12243,13:36 ~ 14:24,14:24 ~ 15:18
66,Aeroporto Internacional Pinto Martins,659,00:43 ~ 00:46,00:46 ~ 00:49,1011,01:07 ~ 01:11,01:11 ~ 01:15,1222.0,01:21 ~ 01:26,01:26 ~ 01:31,...,00:44 ~ 00:46,498.0,00:33 ~ 00:35,00:35 ~ 00:37,425,00:28 ~ 00:30,00:30 ~ 00:31,809,00:53 ~ 00:57,00:57 ~ 01:00

In [186]:
# Ordena o DataFrame pela coluna "Distrito Federal (Km)"
df_result_sorted = df_result.reset_index(drop=True)

# Exporta o DataFrame ordenado para um arquivo CSV
df_result_sorted.to_csv('./csv_gerado/Tabela_Completa.csv', index=False)

df_result_sorted

,Origem,Alagoas (Km),Alagoas (Hr - Comercial),Alagoas (Hr - Cargueiro),Bahia (Km),Bahia (Hr - Comercial),Bahia (Hr - Cargueiro),Ilhéus (Km),Ilhéus (Hr - Comercial),Ilhéus (Hr - Cargueiro),...,Pernambuco (Hr - Cargueiro),Piauí (Km),Piauí (Hr - Comercial),Piauí (Hr - Cargueiro),Rio Grande do Norte (Km),Rio Grande do Norte (Hr - Comercial),Rio Grande do Norte (Hr - Cargueiro),Sergipe (Km),Sergipe (Hr - Comercial),Sergipe (Hr - Cargueiro)
0,Aeroporto Internacional de João Pessoa,227,00:15 ~ 00:16,00:16 ~ 00:17,737,00:49 ~ 00:52,00:52 ~ 00:55,958.0,01:03 ~ 01:07,01:07 ~ 01:11,...,00:07 ~ 00:08,902.0,01:00 ~ 01:03,01:03 ~ 01:07,155,00:10 ~ 00:10,00:10 ~ 00:11,480,00:32 ~ 00:33,00:33 ~ 00:36
1,Aeroporto de Teresina,898,00:59 ~ 01:03,01:03 ~ 01:07,999,01:06 ~ 01:10,01:10 ~ 01:14,1156.0,01:17 ~ 01:21,01:21 ~ 01:26,...,01:06 ~ 01:10,NaN,None,None,843,00:56 ~ 00:59,00:59 ~ 01:03,909,01:00 ~ 01:04,01:04 ~ 01:08
2,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,07:45 ~ 08:12,08:12 ~ 08:43,7099,07:53 ~ 08:21,08:21 ~ 08:52,7206.0,08:00 ~ 08:28,08:28 ~ 09:00,...,08:12 ~ 08:43,6124.0,06:48 ~ 07:12,07:12 ~ 07:39,6768,07:31 ~ 07:57,07:57 ~ 08:27,7032,07:48 ~ 08:16,08:16 ~ 08:47
3,Aeroporto de Copenhague,7479,08:18 ~ 08:47,08:47 ~ 09:20,7965,08:50 ~ 09:22,09:22 ~ 09:57,8188.0,09:05 ~ 09:37,09:37 ~ 10:14,...,08:39 ~ 09:11,7273.0,08:04 ~ 08:33,08:33 ~ 09:05,7116,07:54 ~ 08:22,08:22 ~ 08:53,7719,08:34 ~ 09:04,09:04 ~ 09:38
4,Aeroporto Jorge Amado,732,00:48 ~ 00:51,00:51 ~ 00:54,224,00:14 ~ 00:15,00:15 ~ 00:16,NaN,None,None,...,01:01 ~ 01:04,1156.0,01:17 ~ 01:21,01:21 ~ 01:26,1082,01:12 ~ 01:16,01:16 ~ 01:21,478,00:31 ~ 00:33,00:33 ~ 00:35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Aeroporto Internacional de Pyongyang Sunan,16188,17:59 ~ 19:02,19:02 ~ 20:14,16696,18:33 ~ 19:38,19:38 ~ 20:52,16919.0,18:47 ~ 19:54,19:54 ~ 21:08,...,18:53 ~ 20:04,16048.0,17:49 ~ 18:52,18:52 ~ 20:03,15838,17:35 ~ 18:37,18:37 ~ 19:47,16441,18:16 ~ 19:20,19:20 ~ 20:33
63,Aeroporto Internacional de Pequim Capital,15617,17:21 ~ 18:22,18:22 ~ 19:31,16130,17:55 ~ 18:58,18:58 ~ 20:09,16347.0,18:09 ~ 19:13,19:13 ~ 20:26,...,18:12 ~ 19:21,15617.0,17:21 ~ 18:22,18:22 ~ 19:31,15285,16:59 ~ 17:58,17:58 ~ 19:06,15873,17:38 ~ 18:40,18:40 ~ 19:50
64,Aeroporto Internacional de Xangai Pudong,16641,18:29 ~ 19:34,19:34 ~ 20:48,17150,19:03 ~ 20:10,20:10 ~ 21:26,17357.0,19:17 ~ 20:25,20:25 ~ 21:41,...,19:25 ~ 20:37,16706.0,18:33 ~ 19:39,19:39 ~ 20:52,16326,18:08 ~ 19:12,19:12 ~ 20:24,16896,18:46 ~ 19:52,19:52 ~ 21:07
65,Aeroporto Internacional de Nursultan Nazarbayev,11988,13:19 ~ 14:06,14:06 ~ 14:59,12498,13:53 ~ 14:42,14:42 ~ 15:37,12708.0,14:07 ~ 14:57,14:57 ~ 15:53,...,13:56 ~ 14:48,12128.0,13:28 ~ 14:16,14:16 ~ 15:09,11673,12:58 ~ 13:43,13:43 ~ 14:35,12243,13:36 ~ 14:24,14:24 ~ 15:18
66,Aeroporto Internacional Pinto Martins,659,00:43 ~ 00:46,00:46 ~ 00:49,1011,01:07 ~ 01:11,01:11 ~ 01:15,1222.0,01:21 ~ 01:26,01:26 ~ 01:31,...,00:44 ~ 00:46,498.0,00:33 ~ 00:35,00:35 ~ 00:37,425,00:28 ~ 00:30,00:30 ~ 00:31,809,00:53 ~ 00:57,00:57 ~ 01:00

# Dataset resumidos - por distância, emissão de CO2, horas de voo em avião comercial e de carga.

In [187]:
# Cria DataFrames separados para distâncias, emissões, tempos comerciais e tempos de carga
df_distancias = df_result.filter(["Origem"] + [f"{estado} (Km)" for estado in aeroportos_estado.keys()])
df_tempo_comercial = df_result.filter(["Origem"] + [f"{estado} (Hr - Comercial)" for estado in aeroportos_estado.keys()])
df_tempo_carga = df_result.filter(["Origem"] + [f"{estado} (Hr - Cargueiro)" for estado in aeroportos_estado.keys()])

# Exporta os DataFrames para arquivos CSV
df_distancias.to_csv('./csv_gerado/Tabela_Distâncias.csv', index=False)
df_tempo_comercial.to_csv('./csv_gerado/Tabela_Tempo_Comercial.csv', index=False)
df_tempo_carga.to_csv('./csv_gerado/Tabela_Tempo_Carga.csv', index=False)

# Exibe o DataFrame de distâncias
df_distancias

,Origem,Alagoas (Km),Bahia (Km),Ilhéus (Km),Ceará (Km),Maranhão (Km),Paraíba (Km),Pernambuco (Km),Piauí (Km),Rio Grande do Norte (Km),Sergipe (Km)
0,Aeroporto Internacional de João Pessoa,227,737,958.0,545,1145,NaN,108,902.0,155,480
1,Aeroporto de Teresina,898,999,1156.0,497,314,902.0,937,NaN,843,909
2,Aeroporto Internacional Hartsfield-Jackson Atl...,6983,7099,7206.0,6353,5818,6897.0,6975,6124.0,6768,7032
3,Aeroporto de Copenhague,7479,7965,8188.0,6997,7065,7255.0,7359,7273.0,7116,7719
4,Aeroporto Jorge Amado,732,224,NaN,1222,1467,958.0,865,1156.0,1082,478
...,...,...,...,...,...,...,...,...,...,...,...
62,Aeroporto Internacional de Pyongyang Sunan,16188,16696,16919.0,15769,15821,15961.0,16057,16048.0,15838,16441
63,Aeroporto Internacional de Pequim Capital,15617,16130,16347.0,15277,15429,15395.0,15483,15617.0,15285,15873
64,Aeroporto Internacional de Xangai Pudong,16641,17150,17357.0,16349,16524,16424.0,16506,16706.0,16326,16896
65,Aeroporto Internacional de Nursultan Nazarbayev,11988,12498,12708.0,11725,12004,11770.0,11852,12128.0,11673,12243
66,Aeroporto Internacional Pinto Martins,659,1011,1222.0,1,647,544.0,625,498.0,425,809

In [188]:
aeroportos_exterior = {
    "Albânia": ["Aeroporto Internacional Madre Teresa (Tirana)"],
    "Alemanha": ["Aeroporto de Frankfurt"],
    "Andorra": [
        "Aeroporto de Barcelona-El Prat (Espanha)",
        "Aeroporto de Toulouse-Blagnac (França)"
    ],
    "Áustria": ["Aeroporto Internacional de Viena"],
    "Bélgica": ["Aeroporto de Bruxelas"],
    "Bulgária": ["Aeroporto de Sófia"],
    "Cazaquistão": ["Aeroporto Internacional de Nursultan Nazarbayev"],
    "China": [
        "Aeroporto Internacional de Xangai Pudong",
        "Aeroporto Internacional de Pequim Capital"
    ],
    "Coreia do Norte": ["Aeroporto Internacional de Pyongyang Sunan"],
    "Coreia do Sul": ["Aeroporto Internacional de Incheon"],
    "Eslováquia": ["Aeroporto de Bratislava"],
    "Eslovênia": ["Aeroporto de Ljubljana Joe Pu?nik"],
    "Espanha": [
        "Aeroporto Adolfo Suárez Madrid-Barajas",
        "Aeroporto de Barcelona-El Prat (Espanha)"
    ],
    "Estônia": ["Aeroporto de Tallinn"],
    "Filipinas": ["Aeroporto Internacional Ninoy Aquino"],
    "Finlândia": ["Aeroporto de Helsinque"],
    "França": ["Aeroporto de Toulouse-Blagnac (França)"],
    "Hong Kong": ["Aeroporto Internacional de Hong Kong"],
    "Hungria": ["Aeroporto Internacional de Budapeste Ferenc Liszt"],
    "Ilhas Faroe": ["Aeroporto de Vágar"],
    "Índia": ["Aeroporto Internacional Indira Gandhi"],
    "Indonésia": [
        "Aeroporto Internacional Soekarno-Hatta (Jacarta)",
        "Aeroporto Internacional Ngurah Rai (Bali)"
    ],
    "Irlanda": ["Aeroporto de Dublin"],
    "Itália": [
        "Aeroporto de Roma-Fiumicino",
        "Aeroporto de Milão-Malpensa"
    ],
    "Japão": [
        "Aeroporto Internacional de Narita (Tóquio)",
        "Aeroporto Internacional de Haneda (Tóquio)",
        "Aeroporto Internacional de Kansai (Osaka)"
    ],
    "Laos": ["Aeroporto Internacional de Wattay (Vientiane)"],
    "Letônia": ["Aeroporto Internacional de Riga"],
    "Lituânia": ["Aeroporto Internacional de Vilnius"],
    "Luxemburgo": ["Aeroporto de Luxemburgo"],
    "Malásia": [
        "Aeroporto Internacional de Kuala Lumpur (Sepang)",
        "Aeroporto Internacional de Penang (Penang)"
    ],
    "Maldivas": ["Aeroporto Internacional de Malé"],
    "Malta": ["Aeroporto Internacional de Malta"],
    "Noruega": ["Aeroporto de Oslo-Gardermoen"],
    "Países Baixos (Holanda)": ["Aeroporto de Schiphol (Amsterdã)"],
    "Polônia": ["Aeroporto de Varsóvia Chopin"],
    "Portugal": [
        "Aeroporto Humberto Delgado (Lisboa)",
        "Aeroporto Francisco Sá Carneiro (Porto)"
    ],
    "Reino Unido": [
        "Aeroporto de Heathrow (Londres)",
        "Aeroporto de Gatwick (Londres)"
    ],
    "República Tcheca": ["Aeroporto de Praga"],
    "Romênia": ["Aeroporto Internacional Henri Coand? (Bucareste)"],
    "Rússia": [
        "Aeroporto Internacional Sheremetyevo (Moscou)",
        "Aeroporto de Pulkovo (São Petersburgo)"
    ],
    "Sérvia": ["Aeroporto Nikola Tesla (Belgrado)"],
    "Singapura": ["Aeroporto Internacional de Changi"],
    "Suécia": ["Aeroporto de Estocolmo-Arlanda"],
    "Suíça": ["Aeroporto de Zurique"],
    "Tailândia": [
        "Aeroporto Internacional de Suvarnabhumi",
        "Aeroporto Internacional Don Mueang"
    ],
    "Taiwan (Formosa)": ["Aeroporto Internacional de Taiwan Taoyuan"],
    "Turquia": ["Aeroporto de Istambul"],
    "Ucrânia": ["Aeroporto Internacional de Boryspil (Kiev)"],
    "Vietnã": [
        "Aeroporto Internacional de Tan Son Nhat",
        "Aeroporto Internacional de Noi Bai"
    ]
}

# Arrumar o dataset Rota_Original

In [189]:
file_path = './csv_recebidos/Voos_Nordeste.csv'  # Arquivo com os nomes dos aeroportos

# Carrega os arquivos CSV em DataFrames
df_nordeste = pd.read_csv(file_path)  # DataFrame com as distâncias
# Remove duplicatas e ordena o DataFrame pelo destino
df_nordeste = df_nordeste.drop_duplicates()
df_nordeste = df_nordeste.sort_values(by="UF do Produto", ascending=True).reset_index(drop=True)
df_nordeste

,UF do Produto,URF,Código NCM,Países,Quantidades - (2020-2025),Frete - (2020-2025),Frete Total
0,Alagoas,Aeroporto Internacional de Guarulhos,84715010,Estados Unidos,10,1091,10910
1,Alagoas,Aeroporto Internacional de Guarulhos,84715010,China,3,353,1059
2,Alagoas,Aeroporto Internacional do Recife,84715010,"Tcheca, República",1,59,59
3,Alagoas,Aeroporto Internacional de Guarulhos,84715010,México,25,3246,81150
4,Alagoas,Aeroporto Internacional de Viracopos,84715010,China,1,17,17
...,...,...,...,...,...,...,...
343,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,84715010,Dinamarca,8,968,7744
344,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,84715010,Dinamarca,1,120,120
345,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,84715010,Alemanha,1,237,237
346,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,84715010,China,4,85,340
347,Sergipe,Aeroporto Internacional de Guarulhos,84715010,China,50,630,31500

# Rotas Originais

In [190]:
aeroportos_nordeste = {"Alagoas": ["Aeroporto Internacional de Maceió"],
    "Bahia": ["Aeroporto Internacional de Salvador"],
    "Ilhéus": ["Aeroporto Jorge Amado"],
    "Ceará": ["Aeroporto Internacional de Fortaleza"],
    "Maranhão": ["Aeroporto Internacional de São Luís"],
    "Paraíba": ["Aeroporto Internacional de João Pessoa"],
    "Pernambuco": ["Aeroporto Internacional do Recife"],
    "Piauí": ["Aeroporto de Teresina"],
    "Rio Grande do Norte": ["Aeroporto Internacional de Natal"],
    "Sergipe": ["Aeroporto Internacional de Aracaju"]}

lista_estados = list(aeroportos_nordeste.keys())
lista_estados

['Alagoas',
 'Bahia',
 'Ilhéus',
 'Ceará',
 'Maranhão',
 'Paraíba',
 'Pernambuco',
 'Piauí',
 'Rio Grande do Norte',
 'Sergipe']

In [191]:
aeroportos_nome = {
    "Aeroporto Internacional de Guarulhos": "SP-Guarulhos",
    "Aeroporto Internacional do Recife": "PE",
    "Aeroporto Internacional de Salvador": "BA",
    "Aeroporto Internacional de Natal": "RN",
    "Aeroporto Internacional de São Luís": "MA",
    "Aeroporto Internacional Pinto Martins": "CE",
    "Aeroporto Internacional de Nursultan Nazarbayev": "KAZ",
    "Aeroporto Internacional de Xangai Pudong": "CHN-Xangai",
    "Aeroporto Internacional de Pequim Capital": "CHN-Pequim",
    "Aeroporto Internacional de Pyongyang Sunan": "PRK",
    "Aeroporto Internacional de Incheon": "KOR",
    "Aeroporto Internacional Ninoy Aquino": "PHL",
    "Aeroporto Internacional de Hong Kong": "HKG",
    "Aeroporto Internacional Indira Gandhi": "IND-Delhi",
    "Aeroporto Internacional Soekarno-Hatta (Jacarta)": "IDN-Jakarta",
    "Aeroporto Internacional Ngurah Rai (Bali)": "IDN-Bali",
    "Aeroporto Internacional de Narita (Tóquio)": "JPN-Narita",
    "Aeroporto Internacional de Haneda (Tóquio)": "JPN-Haneda",
    "Aeroporto Internacional de Kansai (Osaka)": "JPN-Kansai",
    "Aeroporto Internacional de Wattay (Vientiane)": "LAO",
    "Aeroporto Internacional de Kuala Lumpur (Sepang)": "MYS",
    "Aeroporto Internacional de Penang (Penang)": "MYS-Penang",
    "Aeroporto Internacional de Malé": "MDV",
    "Aeroporto Internacional de Changi": "SGP",
    "Aeroporto Internacional de Suvarnabhumi": "THA-Bangkok",
    "Aeroporto Internacional Don Mueang": "THA-DonMueang",
    "Aeroporto Internacional de Taiwan Taoyuan": "TWN",
    "Aeroporto Internacional de Tan Son Nhat": "VNM-HoChiMinh",
    "Aeroporto Internacional de Noi Bai": "VNM-Hanoi",
    "Aeroporto de Frankfurt": "DEU-Frankfurt",
    "Aeroporto de Dublin": "IRL",
    "Aeroporto de Varsóvia Chopin": "POL",
    "Aeroporto de Oslo-Gardermoen": "NOR",
    "Aeroporto de Roma-Fiumicino": "ITA-Roma",
    "Aeroporto de Milão-Malpensa": "ITA-Milao",
    "Aeroporto de Praga": "CZE",
    "Aeroporto de Heathrow (Londres)": "GBR-Heathrow",
    "Aeroporto de Gatwick (Londres)": "GBR-Gatwick",
    "Aeroporto Internacional de Budapeste Ferenc Liszt": "HUN",
    "Aeroporto de Schiphol (Amsterdã)": "NLD",
    "Aeroporto Internacional de Boryspil (Kiev)": "UKR",
    "Aeroporto de Istambul": "TUR",
    "Aeroporto de Zurique": "CHE",
    "Aeroporto de Estocolmo-Arlanda": "SWE",
    "Aeroporto Nikola Tesla (Belgrado)": "SRB",
    "Aeroporto Internacional Sheremetyevo (Moscou)": "RUS-Moscou",
    "Aeroporto de Pulkovo (São Petersburgo)": "RUS-SPetersburgo",
    "Aeroporto Internacional Henri Coand? (Bucareste)": "ROU",
    "Aeroporto Humberto Delgado (Lisboa)": "PRT-Lisboa",
    "Aeroporto Francisco Sá Carneiro (Porto)": "PRT-Porto",
    "Aeroporto Internacional de Malta": "MLT",
    "Aeroporto de Luxemburgo": "LUX",
    "Aeroporto Internacional de Vilnius": "LTU",
    "Aeroporto Internacional de Riga": "LVA",
    "Aeroporto Internacional Madre Teresa (Tirana)": "ALB",
    "Aeroporto de Barcelona-El Prat (Espanha)": "ESP-Barcelona",
    "Aeroporto de Toulouse-Blagnac (França)": "FRA-Toulouse",
    "Aeroporto Internacional de Viena": "AUT",
    "Aeroporto de Bruxelas": "BEL",
    "Aeroporto de Sófia": "BGR",
    "Aeroporto de Bratislava": "SVK",
    "Aeroporto de Ljubljana Joe Pu?nik": "SVN",
    "Aeroporto Adolfo Suárez Madrid-Barajas": "ESP-Madrid",
    "Aeroporto de Barcelona-El Prat": "ESP-Barcelona",
    "Aeroporto de Tallinn": "EST",
    "Aeroporto de Vágar": "FRO",
    "Aeroporto de Helsinque": "FIN",
    "Aeroporto Internacional de Brasília": "DF",
    "Aeroporto Internacional de Várzea Grande": "MT",
    "Aeroporto Internacional de Belém": "PA",
    "Aeroporto Internacional de Tabatinga": "AM-Tabatinga",
    "Aeroporto Internacional de Manaus": "AM-Manaus",
    "Aeroporto Internacional de Macapá": "AP",
    "Aeroporto Internacional de Fortaleza": "CE",
    "Aeroporto Internacional de Maceió": "AL",
    "Aeroporto Internacional de Aracaju": "SE",
    "Aeroporto Internacional de Belo Horizonte": "MG",
    "Aeroporto Santos Dumont": "RJ-SantosDumont",
    "Aeroporto Internacional do Rio de Janeiro": "RJ-Galeão",
    "Aeroporto Internacional de Vitória": "ES",
    "Aeroporto Internacional de São José dos Campos": "SP-SJC",
    "Aeroporto Internacional de Viracopos": "SP-Viracopos",
    "Aeroporto Internacional de Curitiba": "PR",
    "Aeroporto Internacional de Florianópolis": "SC-Florianopolis",
    "Aeroporto Internacional de Navegantes": "SC-Navegantes",
    "Aeroporto Internacional de Porto Alegre": "RS",
    "Aeroporto Jorge Amado": "BA-Ilheus",
    "Aeroporto de Copenhague": "DNK",
    "Aeroporto Internacional Hartsfield-Jackson Atlanta": "USA-Atlanta",
    "Aeroporto de Teresina": "PI",
    "Aeroporto Internacional de João Pessoa": "PB"
}

In [192]:
# Dicionário para armazenar as rotas por estado
aeroportos_rotas = {}

# Preenche o dicionário com as rotas de cada estado
for i in lista_estados:
    df_aux = df_nordeste.loc[df_nordeste['UF do Produto'] == i]
    u = df_aux['Países'].unique()
    paises = u.tolist()
    aeroporto = []
    for j in paises:
        if j in aeroportos_exterior.keys():
            for k in aeroportos_exterior[j]:
                aeroporto.append(k)
    aeroportos_rotas[i] = aeroporto


aeroportos_rotas['Bahia']

['Aeroporto Internacional de Narita (Tóquio)',
 'Aeroporto Internacional de Haneda (Tóquio)',
 'Aeroporto Internacional de Kansai (Osaka)',
 'Aeroporto de Estocolmo-Arlanda',
 'Aeroporto Internacional de Xangai Pudong',
 'Aeroporto Internacional de Pequim Capital',
 'Aeroporto de Varsóvia Chopin',
 'Aeroporto Internacional de Taiwan Taoyuan',
 'Aeroporto de Frankfurt',
 'Aeroporto Internacional de Suvarnabhumi',
 'Aeroporto Internacional Don Mueang',
 'Aeroporto de Schiphol (Amsterdã)',
 'Aeroporto Adolfo Suárez Madrid-Barajas',
 'Aeroporto de Barcelona-El Prat (Espanha)',
 'Aeroporto de Toulouse-Blagnac (França)',
 'Aeroporto Internacional de Budapeste Ferenc Liszt',
 'Aeroporto Internacional de Viena',
 'Aeroporto de Roma-Fiumicino',
 'Aeroporto de Milão-Malpensa',
 'Aeroporto de Bratislava',
 'Aeroporto de Heathrow (Londres)',
 'Aeroporto de Gatwick (Londres)',
 'Aeroporto Internacional de Changi',
 'Aeroporto Internacional de Kuala Lumpur (Sepang)',
 'Aeroporto Internacional de Penang (Penang)',
 'Aeroporto Internacional de Tan Son Nhat',
 'Aeroporto Internacional de Noi Bai']

In [193]:
dados = []  # Lista para armazenar os dados estruturados

for estado in lista_estados:
    df_aux = df_nordeste.loc[df_nordeste['UF do Produto'] == estado]
    
    for _, linha in df_aux.iterrows():
        aeroporto_nacional = linha['URF']
        origem = linha['Países']
        
        if origem in aeroportos_exterior.keys():
            for aeroporto_internacional in aeroportos_exterior[origem]:
                dados.append({
                    "Estado": estado,
                    "Aeroporto": aeroporto_nacional,
                    "Origem": aeroporto_internacional
                })

# Criar o DataFrame a partir da lista de dicionários
rotas_originais = pd.DataFrame(dados)
rotas_originais

,Estado,Aeroporto,Origem
0,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Xangai Pudong
1,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Pequim Capital
2,Alagoas,Aeroporto Internacional de Viracopos,Aeroporto Internacional de Xangai Pudong
3,Alagoas,Aeroporto Internacional de Viracopos,Aeroporto Internacional de Pequim Capital
4,Alagoas,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Xangai Pudong
...,...,...,...
354,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,Aeroporto de Frankfurt
355,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Xangai Pudong
356,Rio Grande do Norte,Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Pequim Capital
357,Sergipe,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Xangai Pudong
358,Sergipe,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Pequim Capital

In [194]:
def best_route(alvo,regional):
    for i in regional:
        aux = df[(df['InputID'] == alvo) & (df['TargetID'] == i)]['Distância km'].values[0]
        min = 0
        if min == 0 or aux < min:
            melhor = i
            min = aux
    
    return melhor

def create_table(tabela, edges,internacional,regional,estado,df, eficiencia, velocidade):
    for i in edges:
        aux = {'Destino' : estado}
        if i[0] in internacional:
            if i[1] in regional:
                distancia = df[(df['InputID'] == i[0]) & (df['TargetID'] == i[1])]['Distância km'].values[0]
                aux.update({
                    'Origem' : i[0],
                    'Intermerdiario' : '*',
                    'Final' : i[1],
                    'Distancia' : distancia,
                    'Emissão de CO2' : round((((3.16 * (eficiencia * distancia)) / velocidade) / 1000),2)})
                tabela.append(aux) 
            else:
                target = best_route(i[1],regional)
                distancia = df[(df['InputID'] == i[0]) & (df['TargetID'] == i[1])]['Distância km'].values[0] + df[(df['InputID'] == target) & (df['TargetID'] == i[1])]['Distância km'].values[0]
                aux.update({
                    'Origem' : i[0],
                    'Intermerdiario' : i[1],
                    'Final' : target,
                    'Distancia' : distancia,
                    'Emissão de CO2' : round((((3.16 * (eficiencia * distancia)) / velocidade) / 1000),2)
                    },)
                tabela.append(aux) 
    return tabela

In [195]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Função para calcular distâncias entre aeroportos
def achar_distancias(lista_nacionais, lista_interesse, df):
    df_filtrado = df[
        (df['InputID'].isin(lista_nacionais)) &
        (df['TargetID'].isin(lista_interesse))
    ]
    distancias = {}
    for nacional in lista_nacionais:
        distancias[nacional] = {}
        for interesse in lista_interesse:
            distancia = df_filtrado[
                (df_filtrado['InputID'] == nacional) & 
                (df_filtrado['TargetID'] == interesse)
            ]['Distância km']
            distancias[nacional][interesse] = distancia.values[0] if not distancia.empty else None
    return distancias

# Função para carregar o grafo a partir do DataFrame
def load_graph_from_df(df, rotas, source_airports, interest_airports, local_airport):
    distancia = achar_distancias(interest_airports, local_airport, df)

    G = nx.DiGraph()
    for _, linha in rotas.iterrows():
        source = linha['Origem']
        target = linha['Aeroporto']
        df_filtrado = df[(df['InputID'] == source) & (df['TargetID'] == target)]

        if not df_filtrado.empty:
            d = df_filtrado['Distância km'].values[0]
            # Soma com a menor distância adicional do aeroporto de interesse até um local
            d2 = min([distancia.get(target, {}).get(local, 0) or 0 for local in local_airport]) if local_airport else 0
            d_total = d + d2
            tempo = d_total / 875
            weight = ((3.16 * (4412.5 * d_total * tempo)) / 875) / 1000

            G.add_edge(source, target, weight=weight)

    for airport in interest_airports:
        for local in local_airport:
            if not G.has_edge(airport, local):
                d = distancia.get(airport, {}).get(local, 0) or 0
                tempo = d / 875
                weight = ((3.16 * (4412.5 * d * tempo)) / 875) / 1000
                G.add_edge(airport, local, weight=weight)

    return G


# Função para destacar as rotas ideais
def highlight_routes(G, international_airports, national_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path_to_regional = None
            for regional_airport in regional_airports:
                if regional_airport not in G:
                    continue
                for national_airport in national_airports:
                    if national_airport not in G:
                        continue
                    try:
                        path_to_national = nx.shortest_path(G, source=intl_airport, target=national_airport, weight='weight')
                        weight_to_national = nx.path_weight(G, path_to_national, weight='weight')
                        path_to_regional = nx.shortest_path(G, source=national_airport, target=regional_airport, weight='weight')
                        weight_to_regional = nx.path_weight(G, path_to_regional, weight='weight')
                        total_weight = weight_to_national + weight_to_regional
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path_to_regional = path_to_national + path_to_regional[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path_to_regional:
                for i in range(len(best_path_to_regional) - 1):
                    edge = (best_path_to_regional[i], best_path_to_regional[i + 1])
                    ideal_path_edges.add(edge)
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)

def plot_clean_graph(G, ideal_path_edges, interest_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    # Define as cores dos nós
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }
    
    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in interest_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')
    
    edge_labels = nx.get_edge_attributes(G, 'weight')
    highlighted_labels = {edge: f"{round(weight, 2)}" for edge, weight in edge_labels.items() if edge in ideal_path_edges}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=highlighted_labels, font_size=8, font_color='red')
    
    plt.title(f'{title_suffix}')
    plt.axis('off')
    
    # Adiciona legenda manualmente
    legend_labels = {
        "Destino": 'orange',
        "Nacional": 'lightgreen',
        "Internacional": 'lightblue'
    }
    
    for label, color in legend_labels.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)
    
    plt.savefig(save_path)  # Salva o gráfico
    plt.close()  # Fecha a figura para liberar memória


tabela_rotas_comercial = []
# Loop para processar aeroportos em lotes
for i in aeroportos_nordeste.keys():
    batch_size = 30
    for j in range(0, len(aeroportos_rotas[i]), batch_size):
        subset_origem = aeroportos_rotas[i][j:j + batch_size]
        rotas = rotas_originais[
            (rotas_originais['Estado'] == i) & 
            (rotas_originais['Origem'].isin(subset_origem))
        ]
        aeroportos_intermediarios = []
        for _, linha in rotas.iterrows():
            aeroportos_intermediarios.append(linha['Aeroporto'])

        G = load_graph_from_df(df, rotas, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])        
        tabela_rotas_comercial = create_table(tabela_rotas_comercial,ideal_path_edges,subset_origem, aeroportos_estado[i],i,df,4412.5,875)
        save_path = f"grafos_original_nordeste_co/{i}_{j//batch_size + 1}.png"  # Define o caminho para salvar o gráfico
        plot_clean_graph(G, ideal_path_edges, aeroportos_intermediarios, aeroportos_estado[i], title_suffix=f"{i}", save_path=save_path)

In [196]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Função para calcular distâncias entre aeroportos
def achar_distancias(lista_nacionais, lista_interesse, df):
    df_filtrado = df[
        (df['InputID'].isin(lista_nacionais)) &
        (df['TargetID'].isin(lista_interesse))
    ]
    distancias = {}
    for nacional in lista_nacionais:
        distancias[nacional] = {}
        for interesse in lista_interesse:
            distancia = df_filtrado[
                (df_filtrado['InputID'] == nacional) & 
                (df_filtrado['TargetID'] == interesse)
            ]['Distância km']
            distancias[nacional][interesse] = distancia.values[0] if not distancia.empty else None
    return distancias

def load_graph_from_df(df, rotas, source_airports, interest_airports, local_airport):
    distancia = achar_distancias(interest_airports, local_airport, df)

    G = nx.DiGraph()

    for _, linha in rotas.iterrows():
        source = linha['Origem']
        target = linha['Aeroporto']

        df_filtrado = df[(df['InputID'] == source) & (df['TargetID'] == target)]
        if not df_filtrado.empty:
            distancia_directa = df_filtrado['Distância km'].values[0]

            # Considera todos os destinos locais possíveis a partir do 'target'
            d2_total = 0
            for local in local_airport:
                d2 = distancia.get(target, {}).get(local, 0) or 0
                d2_total += d2  # Acumula as distâncias se houver múltiplos destinos possíveis

            d1 = distancia_directa + d2_total
            tempo = d1 / 825  # Tempo estimado com base na distância total
            weight = ((3.16 * (5625 * d1 * tempo)) / 825) / 1000

            G.add_edge(source, target, weight=weight)

    # Adiciona as conexões dos aeroportos intermediários para os locais, se não existirem
    for airport in interest_airports:
        for local in local_airport:
            if not G.has_edge(airport, local):
                d2 = distancia.get(airport, {}).get(local, 0) or 0
                tempo = d2 / 825
                weight = ((3.16 * (5625 * d2 * tempo)) / 825) / 1000
                G.add_edge(airport, local, weight=weight)

    return G


# Função para destacar as rotas ideais
def highlight_routes(G, international_airports, national_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path_to_regional = None
            for regional_airport in regional_airports:
                if regional_airport not in G:
                    continue
                for national_airport in national_airports:
                    if national_airport not in G:
                        continue
                    try:
                        path_to_national = nx.shortest_path(G, source=intl_airport, target=national_airport, weight='weight')
                        weight_to_national = nx.path_weight(G, path_to_national, weight='weight')
                        path_to_regional = nx.shortest_path(G, source=national_airport, target=regional_airport, weight='weight')
                        weight_to_regional = nx.path_weight(G, path_to_regional, weight='weight')
                        total_weight = weight_to_national + weight_to_regional
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path_to_regional = path_to_national + path_to_regional[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path_to_regional:
                for i in range(len(best_path_to_regional) - 1):
                    edge = (best_path_to_regional[i], best_path_to_regional[i + 1])
                    ideal_path_edges.add(edge)
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)


def plot_clean_graph(G, ideal_path_edges, interest_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    # Define as cores dos nós
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }
    
    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in interest_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')
    
    edge_labels = nx.get_edge_attributes(G, 'weight')
    highlighted_labels = {edge: f"{round(weight,2)}" for edge, weight in edge_labels.items() if edge in ideal_path_edges}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=highlighted_labels, font_size=8, font_color='red')
    
    plt.title(f'{title_suffix}')
    plt.axis('off')
    
    # Adiciona legenda manualmente
    legend_labels = {
        "Destino": 'orange',
        "Nacional": 'lightgreen',
        "Internacional": 'lightblue'
    }
    
    for label, color in legend_labels.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)
    
    plt.savefig(save_path)  # Salva o gráfico
    plt.close()  # Fecha a figura para liberar memória
    
tabela_rotas_carga = []
# Loop para processar aeroportos em lotes
for i in aeroportos_nordeste.keys():
    batch_size = 30
    for j in range(0, len(aeroportos_rotas[i]), batch_size):
        subset_origem = aeroportos_rotas[i][j:j + batch_size]
        rotas = rotas_originais[
            (rotas_originais['Estado'] == i) & 
            (rotas_originais['Origem'].isin(subset_origem))
        ]
        aeroportos_intermediarios = []
        for _, linha in rotas.iterrows():
            aeroportos_intermediarios.append(linha['Aeroporto'])

        G = load_graph_from_df(df, rotas, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_intermediarios, aeroportos_estado[i])        
        tabela_rotas_carga = create_table(tabela_rotas_carga,ideal_path_edges,subset_origem, aeroportos_estado[i],i,df,5625,825)
        save_path = f"grafos_rota_carga/{i}_{j//batch_size + 1}.png"  # Define o caminho para salvar o gráfico
        plot_clean_graph(G, ideal_path_edges, aeroportos_intermediarios, aeroportos_estado[i], title_suffix=f"{i}", save_path=save_path)

In [197]:
tabela_rotas_comercial = pd.DataFrame(tabela_rotas_comercial)
tabela_rotas_carga = pd.DataFrame(tabela_rotas_carga)

# Exporta o DataFrame ordenado para um arquivo CSV
tabela_rotas_comercial.to_csv('./csv_gerado/Tabela_Rotas_Comercial.csv', index=False)
tabela_rotas_carga.to_csv('./csv_gerado/Tabela_Rotas_Carga.csv', index=False)

tabela_rotas_comercial

,Destino,Origem,Intermerdiario,Final,Distancia,Emissão de CO2
0,Alagoas,Aeroporto Internacional de Pequim Capital,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Maceió,19539,311.36
1,Alagoas,Aeroporto Internacional de Xangai Pudong,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Maceió,20542,327.35
2,Alagoas,Aeroporto de Frankfurt,Aeroporto Internacional do Recife,Aeroporto Internacional de Maceió,7829,124.76
3,Bahia,Aeroporto de Schiphol (Amsterdã),*,Aeroporto Internacional de Salvador,8323,132.63
4,Bahia,Aeroporto de Gatwick (Londres),Aeroporto Internacional de Viracopos,Aeroporto Internacional de Salvador,10985,175.05
...,...,...,...,...,...,...
91,Rio Grande do Norte,Aeroporto de Roma-Fiumicino,Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,7583,120.84
92,Rio Grande do Norte,Aeroporto de Milão-Malpensa,Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,7634,121.65
93,Rio Grande do Norte,Aeroporto de Zurique,Aeroporto Internacional do Recife,Aeroporto Internacional de Natal,7760,123.66
94,Sergipe,Aeroporto Internacional de Pequim Capital,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Aracaju,19283,307.28
95,Sergipe,Aeroporto Internacional de Xangai Pudong,Aeroporto Internacional de Guarulhos,Aeroporto Internacional de Aracaju,20286,323.27

# Rotas pelo HUB

In [198]:
# Lista de aeroportos Hub (principais)
aeroportos_Hub = [
    "Aeroporto Internacional do Recife",
    "Aeroporto Internacional de Salvador",
    "Aeroporto Internacional de Natal",
    "Aeroporto Internacional de São Luís",
    "Aeroporto Internacional de Fortaleza"
]

In [ ]:
# Dicionário para armazenar as rotas por estado
aeroportos_rotas = {}

# Preenche o dicionário com as rotas de cada estado
for i in lista_estados:
    df_aux = df_nordeste.loc[df_nordeste[''] == i]
    u = df_aux['Origem'].unique()
    paises = u.tolist()
    aeroporto = []
    for j in paises:
        if j in aeroportos_exterior.keys():
            for k in aeroportos_exterior[j]:
                aeroporto.append(k)
    aeroportos_rotas[i] = aeroporto

aeroportos_rotas['Alagoas']

KeyError: 'Destino'

In [ ]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Função para calcular distâncias entre aeroportos
def achar_distancias(lista_nacionais, lista_interesse, df):
    df_filtrado = df[
        (df['InputID'].isin(lista_nacionais)) &
        (df['TargetID'].isin(lista_interesse))
    ]
    distancias = {}
    for nacional in lista_nacionais:
        distancias[nacional] = {}
        for interesse in lista_interesse:
            distancia = df_filtrado[
                (df_filtrado['InputID'] == nacional) & 
                (df_filtrado['TargetID'] == interesse)
            ]['Distância km']
            distancias[nacional][interesse] = distancia.values[0] if not distancia.empty else None
    return distancias

# Função para carregar o grafo a partir do DataFrame
def load_graph_from_df(df, source_airports, interest_airports, local_airport):
    distancia = achar_distancias(interest_airports, local_airport, df)
    filtered_df = df[
        (df['InputID'].isin(source_airports)) & 
        (df['TargetID'].isin(interest_airports))
    ]
    G = nx.DiGraph()
    for _, linha in filtered_df.iterrows():
        source = linha['InputID']
        target = linha['TargetID']
        weight = ((3.16 * (4412.5 * (linha['Distância km']))) / 875) / 1000
        if target not in local_airport:
            for i in local_airport:
                G.add_edge(source, target, weight=weight)
    for airport in interest_airports:
        for local in local_airport:
            if not G.has_edge(airport, local):
                weight = ((3.16 * (4412.5 * (distancia.get(airport, {}).get(local, 0) or 0))) / 875) / 1000
                G.add_edge(airport, local, weight=weight)
    return G

# Função para destacar as rotas ideais
def highlight_routes(G, international_airports, national_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path_to_regional = None
            for regional_airport in regional_airports:
                if regional_airport not in G:
                    continue
                for national_airport in national_airports:
                    if national_airport not in G:
                        continue
                    try:
                        path_to_national = nx.shortest_path(G, source=intl_airport, target=national_airport, weight='weight')
                        weight_to_national = nx.path_weight(G, path_to_national, weight='weight')
                        path_to_regional = nx.shortest_path(G, source=national_airport, target=regional_airport, weight='weight')
                        weight_to_regional = nx.path_weight(G, path_to_regional, weight='weight')
                        total_weight = weight_to_national + weight_to_regional
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path_to_regional = path_to_national + path_to_regional[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path_to_regional:
                for i in range(len(best_path_to_regional) - 1):
                    edge = (best_path_to_regional[i], best_path_to_regional[i + 1])
                    ideal_path_edges.add(edge)
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)


def plot_clean_graph(G, ideal_path_edges, interest_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    # Define as cores dos nós
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }
    
    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in interest_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')
    
    edge_labels = nx.get_edge_attributes(G, 'weight')
    highlighted_labels = {edge: f"{round(weight,2)}" for edge, weight in edge_labels.items() if edge in ideal_path_edges}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=highlighted_labels, font_size=8, font_color='red')
    
    plt.title(f'{title_suffix}')
    plt.axis('off')
    
    # Adiciona legenda manualmente
    legend_labels = {
        "Destino": 'orange',
        "Nacional": 'lightgreen',
        "Internacional": 'lightblue'
    }
    
    for label, color in legend_labels.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)
    
    plt.savefig(save_path)  # Salva o gráfico
    plt.close()  # Fecha a figura para liberar memória

tabela_hub_comercial = []
# Loop para processar aeroportos em lotes
for i in aeroportos_estado.keys():
    batch_size = 30
    for j in range(0, len(aeroportos_rotas[i]), batch_size):
        subset_origem = aeroportos_rotas[i][j:j + batch_size]
        G = load_graph_from_df(df, subset_origem, aeroportos_Hub, aeroportos_estado[i])
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_Hub, aeroportos_estado[i])
        tabela_hub_comercial = create_table(tabela_hub_comercial, ideal_path_edges, subset_origem, aeroportos_estado[i], i, df,4412.5,875)
        save_path = f"grafos_hub_comercial/{i}_{j//batch_size + 1}.png"  # Define o caminho para salvar o gráfico
        plot_clean_graph(G, ideal_path_edges, aeroportos_Hub, aeroportos_estado[i], title_suffix=f"{i}", save_path=save_path)

In [ ]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# Função para calcular distâncias entre aeroportos
def achar_distancias(lista_nacionais, lista_interesse, df):
    df_filtrado = df[
        (df['InputID'].isin(lista_nacionais)) &
        (df['TargetID'].isin(lista_interesse))
    ]
    distancias = {}
    for nacional in lista_nacionais:
        distancias[nacional] = {}
        for interesse in lista_interesse:
            distancia = df_filtrado[
                (df_filtrado['InputID'] == nacional) & 
                (df_filtrado['TargetID'] == interesse)
            ]['Distância km']
            distancias[nacional][interesse] = distancia.values[0] if not distancia.empty else None
    return distancias

# Função para carregar o grafo a partir do DataFrame
def load_graph_from_df(df, source_airports, interest_airports, local_airport):
    distancia = achar_distancias(interest_airports, local_airport, df)
    filtered_df = df[
        (df['InputID'].isin(source_airports)) & 
        (df['TargetID'].isin(interest_airports))
    ]
    G = nx.DiGraph()
    for _, linha in filtered_df.iterrows():
        source = linha['InputID']
        target = linha['TargetID']
        weight = ((3.16 * (5625 * (linha['Distância km']))) / 825) / 1000
        if target not in local_airport:
            for i in local_airport:
                G.add_edge(source, target, weight=weight)
    for airport in interest_airports:
        for local in local_airport:
            if not G.has_edge(airport, local):
                d = distancia.get(airport, {}).get(local, 0)or 0
                if d != 0:
                    weight = ((3.16 * (5625 /( distancia.get(airport, {}).get(local, 0)or 0))) / 825) / 1000
                else:
                    weight = d
                G.add_edge(airport, local, weight=weight)
    return G

# Função para destacar as rotas ideais
def highlight_routes(G, international_airports, national_airports, regional_airports):
    ideal_path_edges = set()
    for intl_airport in international_airports:
        if intl_airport not in G:
            continue
        try:
            min_total_weight = float('inf')
            best_path_to_regional = None
            for regional_airport in regional_airports:
                if regional_airport not in G:
                    continue
                for national_airport in national_airports:
                    if national_airport not in G:
                        continue
                    try:
                        path_to_national = nx.shortest_path(G, source=intl_airport, target=national_airport, weight='weight')
                        weight_to_national = nx.path_weight(G, path_to_national, weight='weight')
                        path_to_regional = nx.shortest_path(G, source=national_airport, target=regional_airport, weight='weight')
                        weight_to_regional = nx.path_weight(G, path_to_regional, weight='weight')
                        total_weight = weight_to_national + weight_to_regional
                        if total_weight < min_total_weight:
                            min_total_weight = total_weight
                            best_path_to_regional = path_to_national + path_to_regional[1:]
                    except nx.NetworkXNoPath:
                        continue
            if best_path_to_regional:
                for i in range(len(best_path_to_regional) - 1):
                    edge = (best_path_to_regional[i], best_path_to_regional[i + 1])
                    ideal_path_edges.add(edge)
        except nx.NetworkXNoPath:
            continue
    return list(ideal_path_edges)

# Função para plotar o grafo

def plot_clean_graph(G, ideal_path_edges, interest_airports, local_airports, title_suffix, save_path):
    pos = nx.circular_layout(G)
    plt.figure(figsize=(12, 10))
    
    # Define as cores dos nós
    node_colors = {
        'Destino': 'orange',
        'Nacional': 'lightgreen',
        'Internacional': 'lightblue'
    }
    
    node_color_list = [
        node_colors['Destino'] if node in local_airports else 
        node_colors['Nacional'] if node in interest_airports else 
        node_colors['Internacional']
        for node in G.nodes
    ]
    
    node_labels = {node: aeroportos_nome[node] for node in G.nodes}
    
    nx.draw_networkx_nodes(G, pos, node_color=node_color_list, node_size=800, alpha=0.9)
    
    regular_edges = [edge for edge in G.edges if edge not in ideal_path_edges]
    nx.draw_networkx_edges(G, pos, edgelist=regular_edges, edge_color='gray', alpha=0.5, width=1)
    nx.draw_networkx_edges(G, pos, edgelist=ideal_path_edges, edge_color='red', width=2.5)
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=9, font_color='black')
    
    edge_labels = nx.get_edge_attributes(G, 'weight')
    highlighted_labels = {edge: f"{round(weight, 5)}" for edge, weight in edge_labels.items() if edge in ideal_path_edges}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=highlighted_labels, font_size=8, font_color='red')
    
    plt.title(f'{title_suffix}')
    plt.axis('off')
    
    # Adiciona legenda manualmente
    legend_labels = {
        "Destino": 'orange',
        "Nacional": 'lightgreen',
        "Internacional": 'lightblue'
    }
    
    for label, color in legend_labels.items():
        plt.scatter([], [], c=color, label=label, s=100, alpha=0.9, edgecolors='k')
    
    plt.legend(loc='upper right', title="Legenda", fontsize=10, title_fontsize=11)
    
    plt.savefig(save_path)  # Salva o gráfico
    plt.close()  # Fecha a figura para liberar memória

tabela_hub_carga = []
# Loop para processar aeroportos em lotes
for i in aeroportos_estado.keys():
    batch_size = 30
    for j in range(0, len(aeroportos_rotas[i]), batch_size):
        subset_origem = aeroportos_rotas[i][j:j + batch_size]
        G = load_graph_from_df(df, subset_origem, aeroportos_Hub, aeroportos_estado[i])
        ideal_path_edges = highlight_routes(G, subset_origem, aeroportos_Hub, aeroportos_estado[i])
        tabela_hub_carga = create_table(tabela_hub_carga, ideal_path_edges, subset_origem, aeroportos_estado[i], i, df,5625,825)
        save_path = f"grafos_hub_carga/{i}_{j//batch_size + 1}.png"  # Define o caminho para salvar o gráfico
        plot_clean_graph(G, ideal_path_edges, aeroportos_Hub, aeroportos_estado[i], title_suffix=f"{i}", save_path=save_path)

In [ ]:
tabela_hub_comercial = pd.DataFrame(tabela_hub_comercial)
tabela_hub_carga = pd.DataFrame(tabela_hub_carga)

# Exporta o DataFrame ordenado para um arquivo CSV
tabela_hub_comercial.to_csv('./csv_gerado/Tabela_Hub_Comercial.csv', index=False)
tabela_hub_carga.to_csv('./csv_gerado/Tabela_Hub_Carga.csv', index=False)

tabela_hub_carga

,Destino,Origem,Intermerdiario,Final,Distancia,Emissão de CO2
0,Alagoas,Aeroporto de Gatwick (Londres),Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Maceió,7751,167.00
1,Alagoas,Aeroporto Adolfo Suárez Madrid-Barajas,Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Maceió,6718,144.74
2,Alagoas,Aeroporto Internacional de Taiwan Taoyuan,Aeroporto Internacional de Natal,Aeroporto Internacional de Maceió,17092,368.25
3,Alagoas,Aeroporto de Heathrow (Londres),Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Maceió,7765,167.30
4,Alagoas,Aeroporto Internacional de Hong Kong,Aeroporto Internacional de Natal,Aeroporto Internacional de Maceió,16607,357.81
...,...,...,...,...,...,...
510,Sergipe,Aeroporto Internacional de Haneda (Tóquio),Aeroporto Internacional de São Luís,Aeroporto Internacional de Aracaju,17548,378.08
511,Sergipe,Aeroporto de Frankfurt,Aeroporto Internacional de Fortaleza,Aeroporto Internacional de Aracaju,8280,178.40
512,Sergipe,Aeroporto Internacional Don Mueang,Aeroporto Internacional de Natal,Aeroporto Internacional de Aracaju,15724,338.78
513,Sergipe,Aeroporto Internacional de Budapeste Ferenc Liszt,Aeroporto Internacional de Natal,Aeroporto Internacional de Aracaju,8550,184.21
514,Sergipe,Aeroporto Internacional de Narita (Tóquio),Aeroporto Internacional de São Luís,Aeroporto Internacional de Aracaju,17517,377.41

# Tabela comparativa entre as rotas originais e as propostas

In [ ]:
import pandas as pd

# Função para criar tabela comparativa (distância e emissão)
def criar_tabela_comparativa(tabela_rotas, tabela_hub, tipo):
    tabela_comparativa = tabela_rotas[['Destino', 'Origem', 'Distancia', 'Emissão de CO2']].copy()
    tabela_comparativa.rename(columns={
        'Destino': 'Estado',
        'Distancia': f'Distância original {tipo}',
        'Emissão de CO2': f'Emissão original {tipo}'
    }, inplace=True)

    # Agrupando a tabela_hub por 'Destino' e 'Origem' para calcular a média
    tabela_hub_agrupada = tabela_hub.groupby(['Destino', 'Origem'], as_index=False).agg({
        'Distancia': 'mean',
        'Emissão de CO2': 'mean'
    })

    # Mesclando com a tabela de rotas para obter distância e emissão médias via hub
    tabela_comparativa = tabela_comparativa.merge(
        tabela_hub_agrupada[['Destino', 'Origem', 'Distancia', 'Emissão de CO2']],
        left_on=['Estado', 'Origem'],
        right_on=['Destino', 'Origem'],
        how='left'
    )

    # Renomeando as colunas de distância e emissão via hub
    tabela_comparativa.rename(columns={
        'Distancia': f'Distância hub {tipo}',
        'Emissão de CO2': f'Emissão hub {tipo}'
    }, inplace=True)

    # Removendo a coluna 'Destino' (já renomeada para 'Estado')
    tabela_comparativa.drop(columns=['Destino'], inplace=True)

    return tabela_comparativa

# Criando as tabelas separadas para carga e comercial
tabela_comparativa_carga = criar_tabela_comparativa(tabela_rotas_carga, tabela_hub_carga, "carga")
tabela_comparativa_comercial = criar_tabela_comparativa(tabela_rotas_comercial, tabela_hub_comercial, "comercial")

# Criando tabelas separadas para distância e emissão de CO₂
tabela_distancia_carga = tabela_comparativa_carga[['Origem', 'Estado', 'Distância hub carga', 'Distância original carga']]
tabela_distancia_comercial = tabela_comparativa_comercial[['Origem', 'Estado', 'Distância hub comercial', 'Distância original comercial']]
tabela_emissao_carga = tabela_comparativa_carga[['Origem', 'Estado', 'Emissão hub carga', 'Emissão original carga']]
tabela_emissao_comercial = tabela_comparativa_comercial[['Origem', 'Estado', 'Emissão hub comercial', 'Emissão original comercial']]

# Unindo as tabelas de carga e comercial
tabela_comparativa = tabela_comparativa_carga.merge(
    tabela_comparativa_comercial,
    on=['Origem', 'Estado'],  # Fazendo o merge pelas colunas comuns
    how='outer'  # Mantendo todas as rotas disponíveis
)

# Convertendo colunas numéricas para inteiros (caso seja necessário)
for coluna in [
    'Distância hub carga', 'Distância original carga', 'Distância hub comercial', 'Distância original comercial',
    'Emissão hub carga', 'Emissão original carga', 'Emissão hub comercial', 'Emissão original comercial'
]:
    tabela_comparativa[coluna] = tabela_comparativa[coluna].fillna(0).astype(int)

# Salvando o dataset atualizado
tabela_comparativa.to_csv('./csv_gerado/Tabela_Comparativa.csv', index=False)

# Convertendo colunas numéricas para inteiros (evitando valores NaN)
for df in [tabela_distancia_carga, tabela_distancia_comercial, tabela_emissao_carga, tabela_emissao_comercial]:
    for coluna in df.columns[2:]:  # Começa a partir da terceira coluna (evita 'Origem' e 'Estado')
        df.loc[:, coluna] = df[coluna].fillna(0).astype(int)

# Salvando os arquivos CSV separados
tabela_distancia_carga.to_csv('./csv_gerado/Tabela_Distancia_Carga.csv', index=False)
tabela_distancia_comercial.to_csv('./csv_gerado/Tabela_Distancia_Comercial.csv', index=False)
tabela_emissao_carga.to_csv('./csv_gerado/Tabela_Emissao_Carga.csv', index=False)
tabela_emissao_comercial.to_csv('./csv_gerado/Tabela_Emissao_Comercial.csv', index=False)

# Exibindo os dataframes
tabela_emissao_carga

,Origem,Estado,Emissão hub carga,Emissão original carga
0,Aeroporto de Gatwick (Londres),Alagoas,167.0,245.0
1,Aeroporto Internacional de Pequim Capital,Alagoas,343.0,358.0
2,Aeroporto Internacional de Hong Kong,Alagoas,357.0,430.0
3,Aeroporto Internacional de Xangai Pudong,Alagoas,359.0,380.0
4,Aeroporto Adolfo Suárez Madrid-Barajas,Alagoas,144.0,138.0
...,...,...,...,...
510,Aeroporto Internacional de Budapeste Ferenc Liszt,Sergipe,184.0,194.0
511,Aeroporto Internacional de Suvarnabhumi,Sergipe,339.0,378.0
512,Aeroporto Internacional de Kuala Lumpur (Sepang),Sergipe,335.0,339.0
513,Aeroporto Internacional de Narita (Tóquio),Sergipe,377.0,371.0
514,Aeroporto Internacional de Kansai (Osaka),Sergipe,381.0,372.0

In [ ]:
import pandas as pd

# Função para análise comparativa por estado
def analisar_por_estado(tabela_comparativa, tipo, metrica):
    """
    Analisa qual rota (original ou via hub) é melhor para cada estado com base na métrica fornecida.

    Parâmetros:
        tabela_comparativa (pd.DataFrame): Tabela contendo as distâncias ou emissões de CO2.
        tipo (str): 'carga' ou 'comercial', para diferenciar os tipos de transporte.
        metrica (str): 'Distância' ou 'Emissão', para definir a métrica de comparação.

    Retorna:
        analise (pd.DataFrame): DataFrame com a contagem de casos por estado.
        conclusao (str): Conclusão geral sobre qual rota é melhor.
    """

    col_original = f'{metrica} original {tipo}'
    col_hub = f'{metrica} hub {tipo}'

    # Verifica se as colunas necessárias existem na tabela
    if col_original not in tabela_comparativa.columns or col_hub not in tabela_comparativa.columns:
        raise ValueError(f"As colunas esperadas '{col_original}' e '{col_hub}' não foram encontradas na tabela.")

    # Garantindo que não haja NaN nos cálculos, usando .loc[:] para evitar SettingWithCopyWarning
    tabela_comparativa = tabela_comparativa.copy()  # Garante que estamos trabalhando com uma cópia
    tabela_comparativa.loc[:, col_original] = tabela_comparativa[col_original].fillna(float('inf'))
    tabela_comparativa.loc[:, col_hub] = tabela_comparativa[col_hub].fillna(float('inf'))

    # Agrupando por Estado e aplicando a análise sem incluir as colunas de agrupamento na função apply()
    analise = tabela_comparativa.groupby('Estado', as_index=False)[[col_original, col_hub]].apply(
        lambda x: pd.Series({
            'iguais': (x[col_original] == x[col_hub]).sum(),
            'hub_menor': (x[col_hub] < x[col_original]).sum(),
            'original_menor': (x[col_original] < x[col_hub]).sum()
        })
    )

    # Determinando a melhor rota para cada estado
    analise['Melhor rota'] = analise.apply(
        lambda x: 'Original' if x['original_menor'] >= x['hub_menor'] else 'Proposta',
        axis=1
    )

    # Determinando qual rota é melhor no geral
    total_original_menor = analise['original_menor'].sum()
    total_hub_menor = analise['hub_menor'].sum()

    conclusao = f"\nConclusão geral ({metrica} - {tipo}): " + (
        "A rota original é melhor." if total_original_menor >= total_hub_menor else "A rota via hub é melhor."
    )

    return analise, conclusao


# Executando a análise para cada caso
analise_distancia_carga, conclusao_distancia_carga = analisar_por_estado(tabela_distancia_carga, "carga", "Distância")
analise_distancia_comercial, conclusao_distancia_comercial = analisar_por_estado(tabela_distancia_comercial, "comercial", "Distância")
analise_emissao_carga, conclusao_emissao_carga = analisar_por_estado(tabela_emissao_carga, "carga", "Emissão")
analise_emissao_comercial, conclusao_emissao_comercial = analisar_por_estado(tabela_emissao_comercial, "comercial", "Emissão")

# Exibindo os resultados
print(analise_distancia_carga)
print(conclusao_distancia_carga)

=== Emissão de CO2 - Carga ===
                 Estado  iguais  hub_menor  original_menor Melhor rota
0               Alagoas       1          5               3    Proposta
1                 Amapá       0          0              10    Original
2              Amazonas       1          0              40    Original
3                 Bahia       8          1              24    Original
4                 Ceará       0          0              24    Original
5        Espírito Santo       1          5              35    Original
6              Maranhão       2          3               6    Original
7           Mato Grosso       0          4               0    Proposta
8          Minas Gerais      16          5              23    Original
9                Paraná      23          0              16    Original
10                 Pará       0          7              17    Original
11           Pernambuco       0          1              29    Original
12  Rio Grande do Norte       2          6              10    Original
13    Rio Grande do Sul      20          0              19    Original
14       Rio de Janeiro       9          0              31    Original
15              Roraima       0          0               2    Original
16       Santa Catarina      20          2              17    Original
17              Sergipe       0          6               3    Proposta
18            São Paulo       9          9              40    Original

Conclusão geral (Emissão - carga): A rota original é melhor.

=== Emissão de CO2 - Comercial ===
                 Estado  iguais  hub_menor  original_menor Melhor rota
0               Alagoas       4          5               0    Proposta
1                 Amapá       0          0              10    Original
2              Amazonas       4          0              37    Original
3                 Bahia      25          1               7    Original
4                 Ceará       0          0              24    Original
5        Espírito Santo      22          5              14    Original
6              Maranhão       5          3               3    Original
7           Mato Grosso       0          4               0    Proposta
8          Minas Gerais      29          6               9    Original
9                Paraná      28          0              11    Original
10                 Pará       0         10              14    Original
11           Pernambuco       4          1              25    Original
12  Rio Grande do Norte       3          5              10    Original
13    Rio Grande do Sul      24          0              15    Original
14       Rio de Janeiro      23          0              17    Original
15              Roraima       0          0               2    Original
16       Santa Catarina      24          2              13    Original
17              Sergipe       2          6               1    Proposta
18            São Paulo      12          5              41    Original

Conclusão geral (Emissão - comercial): A rota original é melhor.

C:\Users\Alice\AppData\Local\Temp\ipykernel_3968\737615089.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  analise = df.groupby('Estado').apply(comparar).reset_index()
C:\Users\Alice\AppData\Local\Temp\ipykernel_3968\737615089.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  analise = df.groupby('Estado').apply(comparar).reset_index()

In [ ]:
print(analise_distancia_comercial)
print(conclusao_distancia_comercial)

                 Estado  iguais  hub_menor  original_menor Melhor rota
0               Alagoas       3          5               1    Proposta
1                 Amapá       0          0              10    Original
2              Amazonas       1          0              40    Original
3                 Bahia       6          3              24    Original
4                 Ceará       0          0              24    Original
5        Espírito Santo       4          5              32    Original
6              Maranhão       5          3               3    Original
7           Mato Grosso       0          4               0    Proposta
8          Minas Gerais       9          9              26    Original
9                Paraná       4          0              35    Original
10                 Pará       0         10              14    Original
11           Pernambuco       0          1              29    Original
12  Rio Grande do Norte       2          6              10    Original
13    Rio Grande do Sul       6          1              32    Original
14       Rio de Janeiro       5          0              35    Original
15              Roraima       0          0               2    Original
16       Santa Catarina       6          6              27    Original
17              Sergipe       0          6               3    Proposta
18            São Paulo       3         12              43    Original

Conclusão geral (Distância - comercial): A rota original é melhor.

In [ ]:
print(analise_emissao_carga)
print(conclusao_emissao_carga)

                 Estado  iguais  hub_menor  original_menor Melhor rota
0               Alagoas       1          5               3    Proposta
1                 Amapá       0          0              10    Original
2              Amazonas       1          0              40    Original
3                 Bahia       8          1              24    Original
4                 Ceará       0          0              24    Original
5        Espírito Santo       1          5              35    Original
6              Maranhão       2          3               6    Original
7           Mato Grosso       0          4               0    Proposta
8          Minas Gerais      16          5              23    Original
9                Paraná      23          0              16    Original
10                 Pará       0          7              17    Original
11           Pernambuco       0          1              29    Original
12  Rio Grande do Norte       2          6              10    Original
13    Rio Grande do Sul      20          0              19    Original
14       Rio de Janeiro       9          0              31    Original
15              Roraima       0          0               2    Original
16       Santa Catarina      20          2              17    Original
17              Sergipe       0          6               3    Proposta
18            São Paulo       9          9              40    Original

Conclusão geral (Emissão - carga): A rota original é melhor.

In [ ]:
print(analise_emissao_comercial)
print(conclusao_emissao_comercial)

                 Estado  iguais  hub_menor  original_menor Melhor rota
0               Alagoas       4          5               0    Proposta
1                 Amapá       0          0              10    Original
2              Amazonas       4          0              37    Original
3                 Bahia      25          1               7    Original
4                 Ceará       0          0              24    Original
5        Espírito Santo      22          5              14    Original
6              Maranhão       5          3               3    Original
7           Mato Grosso       0          4               0    Proposta
8          Minas Gerais      29          6               9    Original
9                Paraná      28          0              11    Original
10                 Pará       0         10              14    Original
11           Pernambuco       4          1              25    Original
12  Rio Grande do Norte       3          5              10    Original
13    Rio Grande do Sul      24          0              15    Original
14       Rio de Janeiro      23          0              17    Original
15              Roraima       0          0               2    Original
16       Santa Catarina      24          2              13    Original
17              Sergipe       2          6               1    Proposta
18            São Paulo      12          5              41    Original

Conclusão geral (Emissão - comercial): A rota original é melhor.